// ─── Atlanta Braves Player Data (2026 Season · Updated May 2, 2026) ──────────
// Single source of truth for roster, games, standings, digest, and RSS feeds.
// Season context: 23-10 (.697) — best record in the NL by 7.5 games — after
// an absurd Friday night at Coors Field. Atlanta trailed 6-0 after four
// (Holmes only gave up 4 R / 5 H in 4 IP but the offense couldn't touch
// Quintana), 6-1 after six, then ripped off EIGHT unanswered: scratched a
// run in the 7th, hung a 4-spot in the 8th highlighted by Mauricio Dubón's
// bases-loaded triple, then Michael Harris II — pinch-hitting for Eli White
// in the 9th with the score tied — turned on a 95-mph Tyler Kinley fastball
// for a 2-run go-ahead HR. Olson added his 10th. Didier Fuentes (W, 1-0)
// went 2 scoreless out of the pen; Pierce Johnson worked a clean 9th for
// his first save. The 8-6 final tied the franchise's largest-ever comeback
// at Coors Field. Tonight (Sat May 2, 8:10 PM ET) Chris Sale (5-1, 2.40)
// goes for #6 vs COL RHP Antonio Senzatela (1-3, 5.84); Spencer Strider's
// 2026 MLB debut is locked for Sunday's finale at altitude. Roster moves
// before Friday's game: José Suárez and Joel Payamps DFA'd; Hunter Stratton
// recalled from Triple-A Gwinnett and Anthony Molina selected from
// Gwinnett. Stratton (Achilles surgery rehab finished) gives the bullpen a
// power righty; Molina is a four-pitch strike-thrower / former Rule 5 pick
// claimed off waivers from COL in December. Both Suárez (6.61 ERA in 16.1
// IP, out of options) and Payamps (8.22 ERA, out of options) cleared the
// 40-man. Sean Murphy holds at Gwinnett another 4-5 days for at-bats;
// Ha-Seong Kim continues his Double-A Columbus rehab (mid-May Atlanta
// target). Raisel Iglesias has resumed throwing — minimum-IL stay still
// in play, May 5 first eligible. Hurston Waldrep is set for his first
// post-surgery bullpen this week (June return targeted); Schwellenbach
// (elbow) still has not resumed throwing (second-half hopes, no firm
// timeline). Dodd (oblique), Joe Jiménez (knee), Smith-Shawver and Danny
// Young (TJ) round out the longer-term IL.
//
// Statuses: "active" | "day-to-day" | "questionable" | "il-10" | "il-15" | "il-60" | "suspended" | "departed"
// Assignments: "mlb" | "aaa" | "aa" | "rehab"  (org-level location, orthogonal to injury status)
//   mlb   = on the 26/40-man active roster with the big club
//   aaa   = optioned or stashed at Triple-A Gwinnett (recall candidate)
//   aa    = lower-level depth (rare; used for high-profile prospects only)
//   rehab = on IL + currently on a minor-league rehab assignment
// injuryNote: short description shown on card when not active

export const PLAYERS = [
  // ── STARTING LINEUP ─────────────────────────────────────────────────────────
  {
    id: "acuna",
    name: "Ronald Acuña Jr.",
    number: 13,
    position: "RF",
    positionGroup: "batter",
    lineupSpot: 1,
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 28, experience: 8,
    stats: { avg: .238, obp: .349, slg: .368, ops: .717, hr: 2, rbi: 9, sb: 6, bb: 19, so: 32, games: 34 },
    statNote: "EXITED SAT MAY 2 IN COL with apparent left hamstring tightness — pulled up halfway down the line on a 2nd-inning ground ball, grabbed at his hammy, walked gingerly off and was replaced by Eli White. MRI pending; team won't have full clarity until Sunday or later. He's appeared in all 34 ATL games this season after being limited to 144 G across 2024-25 (post-ACL). Apr 24 2-run HR off Painter remains his last bomb.",
    form: 6.0,
    status: "questionable",
    injuryNote: "Left hamstring tightness suffered in 2nd inning of 9-1 W at Coors (May 2). MRI scheduled; replaced in-game by Eli White. Status TBD pending imaging.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/36185.png",
    assignment: "mlb",
    contract: { years: 8, total: 100000000, guaranteed: 100000000, apy: 12500000, throughYear: 2028 },
    career: [
      { years: "2018–", team: "Atlanta Braves", type: "MLB · 2023 NL MVP · 4x All-Star" },
    ],
  },
  {
    id: "olson",
    name: "Matt Olson",
    number: 28,
    position: "1B",
    positionGroup: "batter",
    lineupSpot: 2,
    bats: "L", throws: "R",
    nationality: "🇺🇸 USA", age: 32, experience: 10,
    stats: { avg: .298, obp: .371, slg: .629, ops: 1.000, hr: 11, rbi: 31, sb: 0, bb: 16, so: 36, games: 34, doubles: 3 },
    statNote: "HR #11 off Brennan Bernardino in Saturday's 9-1 blowout at Coors — went deep again to keep his MLB HR co-lead. Now .298/.371/.629, 1.000 OPS, 11 HR / 31 RBI through 34 G — still a top-five OPS hitter in baseball. Three straight games with a HR (Friday #10 off Kinley in the 8-6 comeback, Wednesday's walk-off vs DET, Saturday at altitude). The engine of Atlanta's MLB-best 24-10 start.",
    form: 9.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/32767.png",
    assignment: "mlb",
    contract: { years: 8, total: 168000000, guaranteed: 168000000, apy: 21000000, throughYear: 2029 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2023 HR title (54)" },
      { years: "2016–2021", team: "Oakland Athletics", type: "MLB" },
    ],
  },
  {
    id: "riley",
    name: "Austin Riley",
    number: 27,
    position: "3B",
    positionGroup: "batter",
    lineupSpot: 3,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 29, experience: 8,
    stats: { avg: .194, obp: .278, slg: .333, ops: .611, hr: 4, rbi: 18, sb: 2, bb: 12, so: 34, games: 33 },
    statNote: "First HR in two weeks — solo shot at Coors Saturday in the 9-1 W, his 4th of the season. Slash line ticks up to .194/.278/.333 (.611 OPS) but the average is still the issue; the bat needs the altitude trip to catalyze a turnaround. 18 RBI through 33 G with the power continuing to flash in spurts.",
    form: 7.8,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/34982.png",
    assignment: "mlb",
    contract: { years: 10, total: 212000000, guaranteed: 212000000, apy: 21200000, throughYear: 2032 },
    career: [
      { years: "2019–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2x Silver Slugger" },
    ],
  },
  {
    id: "ozuna",
    name: "Marcell Ozuna",
    number: 20,
    position: "DH",
    positionGroup: "batter",
    lineupSpot: 4,
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 35, experience: 13,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Left Braves in FA before 2026 — retained in data as historical reference only. See Baldwin/Yastrzemski for current DH reps.",
    form: 0,
    status: "departed",
    injuryNote: "Signed elsewhere in FA. Not on 2026 Braves roster.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/30205.png",
    assignment: "mlb",
    contract: null,
    career: [
      { years: "2020–2025", team: "Atlanta Braves", type: "MLB · 2023 WS · 2x All-Star" },
    ],
  },
  {
    id: "albies",
    name: "Ozzie Albies",
    number: 1,
    position: "2B",
    positionGroup: "batter",
    lineupSpot: 5,
    bats: "S", throws: "R",
    nationality: "🇨🇼 Curaçao", age: 29, experience: 9,
    stats: { avg: .321, obp: .366, slg: .537, ops: .903, hr: 7, rbi: 21, sb: 0, bb: 9, so: 17, games: 33, wOBA: .315, iso: .160 },
    statNote: "Quiet 1-for-5 in Friday's 8-6 comeback at Coors but reached and scored an early run. 2-run HR (#7) off Skubal in the 1st of Apr 29's walk-off W — Atlanta's only damage off the back-to-back AL Cy Young winner — still the signature swing of the homestand; he walked to lead off the 9th and scored on Olson's walk-off bomb. Bat firmly trending up behind Olson and Harris.",
    form: 9.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33783.png",
    assignment: "mlb",
    contract: { years: 7, total: 35000000, guaranteed: 35000000, apy: 5000000, throughYear: 2027 },
    career: [
      { years: "2017–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2021 WS champ" },
    ],
  },
  {
    id: "harris",
    name: "Michael Harris II",
    number: 23,
    position: "CF",
    positionGroup: "batter",
    lineupSpot: 6,
    bats: "L", throws: "R",
    nationality: "🇺🇸 USA", age: 25, experience: 5,
    stats: { avg: .322, obp: .357, slg: .561, ops: .918, hr: 7, rbi: 22, sb: 2, bb: 6, so: 18, games: 31, wrcPlus: null },
    statNote: "MR. CLUTCH STRIKES AGAIN — pinch-hit (for Eli White) 2-run go-ahead HR (#7) off Tyler Kinley in the 9th at Coors Friday capped Atlanta's 8-unanswered comeback from a 6-0 hole, the franchise-tying largest comeback at COL ever. Quad still managed (DH/PH usage), but the bat is in a different gear: now .322/.357/.561 with 7 HR / 22 RBI in 31 games. Apr 24 pinch-hit go-ahead 2-run double off Painter was the prelude.",
    form: 9.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/42470.png",
    assignment: "mlb",
    contract: { years: 8, total: 72000000, guaranteed: 72000000, apy: 9000000, throughYear: 2030 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 2022 NL ROY · Gold Glove" },
    ],
  },
  {
    id: "baldwin",
    name: "Drake Baldwin",
    number: 55,
    position: "C",
    positionGroup: "batter",
    lineupSpot: 7,
    bats: "L", throws: "R",
    nationality: "🇺🇸 USA", age: 25, experience: 2,
    stats: { avg: .322, obp: .395, slg: .550, ops: .945, hr: 8, rbi: 29, sb: 1, bb: 14, so: 29, games: 33 },
    statNote: "GAME-WRECKER AT COORS — 3-for-4 with a 1st-inning 2-run HR off Brennan Bernardino, 4 RBI, and a triple short of the cycle in Saturday's 9-1 rout. Single-game career-high tying 3 hits. Now slashing .322/.395/.550 with 8 HR / 29 RBI through 33 G; bat is locked in as the everyday catcher with Murphy still on rehab. Three multi-hit games in the last week.",
    form: 9.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4810190.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB · 3rd-round 2022 draft (Missouri State)" },
    ],
  },
  {
    id: "profar",
    name: "Jurickson Profar",
    number: 7,
    position: "LF",
    positionGroup: "batter",
    lineupSpot: 8,
    bats: "S", throws: "R",
    nationality: "🇨🇼 Curaçao", age: 33, experience: 14,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Everyday LF in the post-Ozuna outfield rotation.",
    form: 6.9,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/31117.png",
    assignment: "mlb",
    contract: { years: 3, total: 42000000, guaranteed: 42000000, apy: 14000000, throughYear: 2027 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB · 2024 NL All-Star" },
      { years: "2012–2024", team: "Various (TEX, OAK, COL, SD)", type: "MLB" },
    ],
  },
  {
    id: "allen",
    name: "Nick Allen",
    number: 14,
    position: "SS",
    positionGroup: "batter",
    lineupSpot: 9,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 27, experience: 4,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Sharing SS reps with Dubón while Kim rehabs finger tendon. Defense-first profile.",
    form: 6.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40338.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB" },
      { years: "2022–2024", team: "Oakland Athletics", type: "MLB" },
    ],
  },
  {
    id: "yastrzemski",
    name: "Mike Yastrzemski",
    number: 5,
    position: "RF",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 35, experience: 8,
    stats: { avg: .209, obp: .280, slg: .275, ops: .555, hr: 0, rbi: 6, sb: 1, bb: 8, so: 25, games: 29 },
    statNote: "Offseason FA signing struggling out of the gate — .209/.280/.275, no HRs through 29 games. The error on Vierling's bullet through the LF gap on Apr 30 added the dagger run in the 5-2 L. Veteran platoon-piece role still intact while the bat looks for traction.",
    form: 5.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33341.png",
    assignment: "mlb",
    contract: { years: 1, total: 7000000, guaranteed: 7000000, apy: 7000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2019–2025", team: "San Francisco Giants", type: "MLB · 2021 NL All-Star" },
    ],
  },
  {
    id: "dubon",
    name: "Mauricio Dubón",
    number: 2,
    position: "UT",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇭🇳 Honduras", age: 31, experience: 8,
    stats: { avg: .283, obp: .332, slg: .455, ops: .787, hr: 2, rbi: 18, sb: 0, bb: 6, so: 20, games: 31, triples: 1 },
    statNote: "BASES-LOADED TRIPLE in the 8th at Coors Friday — the swing that finished erasing the 6-run hole and tied it 6-6 before Harris's 9th-inning HR sealed it. 2-for-5, 3 RBI on the night. Primary SS while Kim rehabs; rotates through 2B/LF/CF as needed. Now .283/.332/.455 with 18 RBI through 31 games.",
    form: 8.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/35304.png",
    assignment: "mlb",
    contract: { years: 2, total: 8500000, guaranteed: 8500000, apy: 4250000, throughYear: 2027 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2022–2025", team: "Houston Astros", type: "MLB · 2022 & 2023 WS champ" },
    ],
  },

  // ── STARTING ROTATION ───────────────────────────────────────────────────────
  {
    id: "sale",
    name: "Chris Sale",
    number: 51,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 1,
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 37, experience: 15,
    stats: { era: 2.14, whip: 0.83, ip: 42.0, k: 49, bb: 9, hr: null, w: 6, l: 1, games: 7, starts: 7 },
    statNote: "MLB-LEADING 6th W — Sale dominated at altitude Saturday: 7 IP / 3 H / 1 ER / 11 K in the 9-1 rout at Coors. Season line down to 2.14 ERA / 0.83 WHIP across 7 starts; the 49 K leads the NL. Coors as a tune-up for the Strider series finale Sunday. 150th career W in the bag (Apr 26 vs PHI), already past Glavine on the all-time K list (2,608+).",
    form: 9.7,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/30948.png",
    assignment: "mlb",
    contract: { years: 2, total: 54000000, guaranteed: 38000000, apy: 27000000, throughYear: 2027 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB · 2024 NL Cy Young" },
      { years: "2016–2023", team: "Boston Red Sox", type: "MLB · 2018 WS champ" },
      { years: "2010–2016", team: "Chicago White Sox", type: "MLB · 7x All-Star" },
    ],
  },
  {
    id: "lopez",
    name: "Reynaldo López",
    number: 40,
    position: "RP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 32, experience: 10,
    stats: { era: 3.42, whip: 1.31, ip: 23.2, k: 22, bb: 11, hr: null, w: 2, l: 1, games: 6, starts: 5 },
    statNote: "Picked up the W (now 2-1, ERA down to 3.27) in Wednesday's 4-3 walk-off over DET — 2 scoreless / 0 H / 2 K out of the bullpen in the 8th and 9th, setting up Olson's walk-off blast. Second pen outing of the Walt Weiss reset (Apr 27) and a clear sign the slider work is taking. Weiss has said López projects back to the rotation once the mechanical reset is done.",
    form: 7.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33860.png",
    assignment: "mlb",
    contract: { years: 3, total: 30000000, guaranteed: 30000000, apy: 10000000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB · 2024 NL All-Star" },
      { years: "2018–2023", team: "Chicago White Sox", type: "MLB" },
    ],
  },
  {
    id: "holmes",
    name: "Grant Holmes",
    number: 58,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 3,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 30, experience: 3,
    stats: { era: 4.50, whip: 1.40, ip: 36.1, k: 27, bb: 17, w: 2, l: 1, games: 7, starts: 7 },
    statNote: "Got bullied by altitude Friday — 4 IP / 6 H / 4 ER / 3 BB / 2 K, ND in Atlanta's 8-6 comeback W. Quintana matched zeroes through 4 (Holmes left trailing 4-0); the Braves' bullpen and offense bailed him out. ERA up to 4.50 across 7 starts, but the rotation depth absorbs the bad start. Apr 24 W vs PHI (6 IP, 2 ER) still the line-of-the-month for him.",
    form: 7.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33840.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "elder",
    name: "Bryce Elder",
    number: 55,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 4,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 27, experience: 4,
    stats: { era: 1.88, whip: 1.05, ip: 43.0, k: 36, bb: 13, w: 3, l: 1, games: 7, starts: 7 },
    statNote: "Thu 12:15 PM matinee vs DET: 6 IP / 6 H / 1 ER / 3 BB / 5 K, no-decision after exiting with a 2-1 lead in the 5-2 loss (the bullpen lost it). ERA holds at sub-1.90 — Cy-Young-adjacent through 7 starts. The DBacks/Tigers stretch has been the best statistical run by a Braves SP this season.",
    form: 8.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4301067.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 2023 NL All-Star" },
    ],
  },
  {
    id: "suarez-jose",
    name: "José Suárez",
    number: 49,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 5,
    bats: "L", throws: "L",
    nationality: "🇻🇪 Venezuela", age: 28, experience: 7,
    stats: { era: 6.61, whip: 2.08, ip: 16.1, k: 21, bb: 12, w: 0, l: 1, games: 8, starts: 1 },
    statNote: "Designated for assignment May 1 in the corresponding move when Hunter Stratton was recalled. Out of minor-league options, 6.61 ERA across 8 G / 16.1 IP. Took the LP in both the Apr 25 (10) walk-off vs PHI and the Apr 30 5-2 finale vs DET (walked two in the 9th).",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd May 1, 2026 — off the 40-man.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40981.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2019–2025", team: "Los Angeles Angels", type: "MLB" },
    ],
  },
  {
    id: "perez-martin",
    name: "Martín Pérez",
    number: 54,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 6,
    bats: "L", throws: "L",
    nationality: "🇻🇪 Venezuela", age: 35, experience: 14,
    stats: { era: 2.22, whip: 0.99, ip: 28.1, k: 19, bb: 10, w: 2, l: 1, games: 6, starts: 4 },
    statNote: "Picked up the W (now 2-1, 2.07 ERA) in Tuesday's 5-2 over DET — 5 scoreless on 2 H / 4 BB / 5 K in the series opener vs the AL Central champs. First win over Detroit since Aug 25, 2019. Also pitched 6 scoreless in the 9-0 Phillies W on Apr 17.",
    form: 8.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/31098.png",
    assignment: "mlb",
    contract: { years: 1, total: 2000000, guaranteed: 0, apy: 2000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · 2022 AL All-Star" },
      { years: "2012–2025", team: "Various (TEX, BOS, MIN, PIT, CHW)", type: "MLB" },
    ],
  },
  {
    id: "ritchie",
    name: "JR Ritchie",
    number: 48,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 7,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 22, experience: 0,
    stats: { era: 2.92, whip: 1.30, ip: 12.1, k: 11, bb: 6, w: 1, l: 0, games: 2, starts: 2 },
    statNote: "Pitched into the 6th in his second MLB start (Wed Apr 29 vs DET, ND in the 4-3 walk-off W) — Riley Greene solo HR in the 3rd flipped a 2-0 lead, then a Ritchie pickoff-throw error on McGonigle in the 2nd put a runner across to tie it. Charged with 3 R (2 ER) on 4 H / 3 BB / 4 K on 89 pitches. Sensational debut Apr 23 at WSH (7 IP / 2 ER / 7 K / 2 BB) is still a Braves franchise first.",
    form: 8.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5080757.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · MLB debut Apr 23, 2026" },
    ],
  },

  // ── BULLPEN ─────────────────────────────────────────────────────────────────
  {
    id: "iglesias",
    name: "Raisel Iglesias",
    number: 26,
    position: "CP",
    positionGroup: "pitcher",
    bullpenRole: "closer",
    bats: "R", throws: "R",
    nationality: "🇨🇺 Cuba", age: 36, experience: 11,
    stats: { era: 0.00, whip: 0.69, ip: 8.2, k: 11, bb: 1, sv: 5, hold: null, games: 8 },
    statNote: "Resumed throwing this week — Walt Weiss said pre-game Apr 28 that the shoulder inflammation has subsided and he expects Iglesias back when first eligible (May 5) or shortly after. Pre-IL line was spotless: 0.00 ERA on 5 H / 11 K / 1 BB and 5 saves over 8.2 IP.",
    form: 0,
    status: "il-15",
    injuryNote: "Right shoulder inflammation (no structural damage on MRI). 15-day IL backdated to Apr 20. Throwing again as of late April; Weiss targeting his May 5 eligibility date or shortly after. Suarez handling the 9th in the meantime.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33618.png",
    assignment: "mlb",
    contract: { years: 1, total: 16000000, guaranteed: 16000000, apy: 16000000, throughYear: 2026 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 3x 30-save season" },
    ],
  },
  {
    id: "suarez-robert",
    name: "Robert Suarez",
    number: 75,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "closer",
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 35, experience: 4,
    stats: { era: 0.71, whip: 0.87, ip: 12.2, k: 13, bb: 2, sv: 3, hold: null, games: 13 },
    statNote: "Full-time closer since Apr 22. Has converted the save chance since taking over; dominant profile (1 ER / 9.2 IP as a setup man).",
    form: 8.7,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4148749.png",
    assignment: "mlb",
    contract: { years: 3, total: 45000000, guaranteed: 45000000, apy: 15000000, throughYear: 2028 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · 2x All-Star" },
      { years: "2022–2025", team: "San Diego Padres", type: "MLB" },
    ],
  },
  {
    id: "bummer",
    name: "Aaron Bummer",
    number: 48,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "lhp",
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 32, experience: 9,
    stats: { era: 4.35, whip: 1.36, ip: 10.1, k: 8, bb: 4, sv: 0, hold: null, games: 14, w: 0, l: 1 },
    statNote: "LH specialist — 14 G, 10.1 IP, 4.35 ERA. Walked McGonigle in relief Thu in DET's 5-2 sweep-avoiding W; the sac fly that followed went on the books as the go-ahead run. Still a high-leverage piece, but the recent results haven't matched the 98-game ATL track record.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/36131.png",
    assignment: "mlb",
    contract: { years: 2, total: 13000000, guaranteed: 13000000, apy: 6500000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
      { years: "2017–2023", team: "Chicago White Sox", type: "MLB" },
    ],
  },
  {
    id: "lee",
    name: "Dylan Lee",
    number: 52,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "lhp",
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 31, experience: 5,
    stats: { era: 1.23, whip: 0.55, ip: 14.2, k: 17, bb: 2, sv: 0, hold: null, games: 15, w: 1, l: 0 },
    statNote: "Quietly the best arm in the pen — 15 G, 1.23 ERA, 0.55 WHIP, 17 K against just 2 BB across 14.2 IP. Took the 8th in Saturday's loss vs PHI (Schwarber leadoff triple, Harper sac fly) but otherwise lights-out. Top lefty in the pen and still the highest-WAR arm among the Lee/Bummer/Kinley trio.",
    form: 6.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/41455.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2021–", team: "Atlanta Braves", type: "MLB · 2021 WS champ" },
    ],
  },
  {
    id: "kinley",
    name: "Tyler Kinley",
    number: 58,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 35, experience: 7,
    stats: { era: 1.29, whip: 1.14, ip: 14.0, k: 14, bb: 7, sv: 0, hold: null, games: 15, w: 3, l: 1 },
    statNote: "Hard-slider middle-relief arm — 15 G, 1.29 ERA, 14 K / 14 IP. Already 3-1 from middle relief; the offseason signing has been the biggest non-Suarez bullpen value-add of the year.",
    form: 6.8,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/34166.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2020–2025", team: "Colorado Rockies", type: "MLB" },
    ],
  },
  {
    id: "payamps",
    name: "Joel Payamps",
    number: 37,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 31, experience: 6,
    stats: { era: 8.22, whip: 1.70, ip: 7.2, k: 9, bb: 4, sv: 0, hold: null, games: 12, w: 0, l: 2 },
    statNote: "Designated for assignment May 1 alongside José Suárez when Stratton/Molina came up. Out of minor-league options. The Apr 30 lead-loss vs DET (Carpenter triple, Vierling double, walk to McGonigle) was his last Atlanta outing — 8.22 ERA across 12 G / 7.2 IP. The strike-thrower profile flashed (9 K) but the leverage trust never came back after April.",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd May 1, 2026 — off the 40-man.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40021.png",
    assignment: "mlb",
    contract: { years: 1, total: 3000000, guaranteed: 3000000, apy: 3000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2023–2025", team: "Milwaukee Brewers", type: "MLB" },
    ],
  },
  {
    id: "hamilton",
    name: "Ian Hamilton",
    number: 71,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 31, experience: 5,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Designated for assignment Apr 22 to clear a roster spot for Didier Fuentes' spot start. Off the 40-man.",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd Apr 22, 2026 — no longer on the Braves 40-man roster.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/41127.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2023–2025", team: "New York Yankees", type: "MLB" },
    ],
  },
  {
    id: "fuentes",
    name: "Didier Fuentes",
    number: 68,
    position: "SP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "R", throws: "R",
    nationality: "🇨🇴 Colombia", age: 20, experience: 1,
    stats: { era: 4.09, whip: 1.18, ip: 11.0, k: 14, bb: 3, sv: 0, hold: null, games: 4, starts: 1, w: 1, l: 0 },
    statNote: "FIRST CAREER WIN — 2 scoreless out of the pen in Friday's 8-6 comeback at Coors (5th-6th, 3 K, 1 H), inheriting and stranding a runner before Atlanta erupted for 8 unanswered. The 20-year-old (youngest SP in the majors) keeps cementing the long-relief / emergency-start role behind the bullpen. Apr 22 spot start vs WSH: 3 IP / 7 H / 4 ER (Braves still won 8-6).",
    form: 8.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5291189.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · MLB debut" },
    ],
  },
  {
    id: "dodd",
    name: "Dylan Dodd",
    number: 64,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 28, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Apr 22 relief outing at WSH — 1 ER allowed, then came away with an oblique issue. Placed on the 15-day IL Apr 23; Carrasco selected to take his roster spot.",
    form: 0,
    status: "il-15",
    injuryNote: "Left oblique strain suffered in Apr 22 appearance vs WSH. 15-day IL Apr 23 — return window late May at earliest.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4416462.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "carrasco",
    name: "Carlos Carrasco",
    number: 59,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 39, experience: 16,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Designated for assignment Apr 29 — the corresponding move when Dylan Lee was reinstated from the paternity list. Carrasco was selected Apr 23 from Gwinnett (1.71 ERA, 18:5 K:BB over 21 IP) but didn't see meaningful big-league usage before the roster crunch.",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd Apr 29, 2026 — off the 40-man roster.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/30976.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB (2nd stint)" },
      { years: "2009–2024", team: "Various (CLE, NYM, NYY)", type: "MLB · 2017 AL 18-win season" },
    ],
  },
  {
    id: "stratton",
    name: "Hunter Stratton",
    number: 65,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 29, experience: 3,
    stats: { era: 4.50, whip: 1.92, ip: 12.0, k: 18, bb: 5, sv: 0, hold: null, games: 11, w: 2, l: 2 },
    statNote: "RECALLED MAY 1 from Triple-A Gwinnett (one of two corresponding moves with the Suárez/Payamps DFAs). Power righty acquired from Pittsburgh in July 2025 (for Titus Dumitru); had a 2.20 ERA / 15 K across 12 G with Atlanta after the trade before the Aug 24 ruptured patellar tendon ended his 2025. The Achilles/knee rehab is finished — back to full-leverage middle-relief role.",
    form: 7.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4987652.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB" },
      { years: "2023–2025", team: "Pittsburgh Pirates", type: "MLB · debut 2023" },
    ],
  },
  {
    id: "molina-anthony",
    name: "Anthony Molina",
    number: 67,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 24, experience: 2,
    stats: { era: 4.50, whip: 1.36, ip: 14.0, k: 10, bb: 3, sv: 0, hold: null, games: 5, starts: 2, w: 1, l: 2 },
    statNote: "CONTRACT SELECTED MAY 1 from Triple-A Gwinnett alongside Stratton's recall. Four-pitch strike-thrower (4-seam, slider, change, two-seam) claimed off waivers from Colorado in December 2025. Made his MLB debut as a Rule 5 pick on 2024 Opening Day with COL (35 G, 6.79 ERA). Adds long-relief / spot-start depth behind the bullpen with Suárez and Payamps gone.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5016983.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2024–2025", team: "Colorado Rockies", type: "MLB · Rule 5 pick from TB 2023" },
    ],
  },

  // ── TRIPLE-A DEPTH (recall candidates on 40-man, optioned to Gwinnett) ─────
  {
    id: "munoz-rolddy",
    name: "Rolddy Muñoz",
    number: 78,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 26, experience: 2,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Power righty — 97-98 mph FB, slider-heavy. 7.2 scoreless IP / 7 K through first 5 at Gwinnett. Optioned back down when Dodd was recalled Apr 21; next man up in a bullpen emergency.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5131982.png",
    assignment: "aaa",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB · MLB debut 2025" },
    ],
  },

  // ── INJURED LIST ────────────────────────────────────────────────────────────
  {
    id: "strider",
    name: "Spencer Strider",
    number: 99,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 2,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 27, experience: 5,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, w: null, l: null, games: null, starts: null },
    statNote: "ACTIVATED FROM 15-DAY IL TODAY (Sun May 3) — 2026 MLB debut at Coors Field vs COL LHP Kyle Freeland (1-2, 3.48). First big-league outing since the spring oblique strain. Three rehab starts at Triple-A Gwinnett produced 12.2 IP / 18 K / 2 ER, capped by an Apr 26 dress rehearsal of 5 IP / 4 H / 2 ER / 2 BB / 7 K on 82 pitches (17 SwStr), four-seamer 95.2 mph avg / 96.9 peak. Coors as the debut venue is a bold call by Walt Weiss; the team is comfortable enough with the stuff to risk it.",
    form: 8.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4307825.png",
    assignment: "mlb",
    contract: { years: 6, total: 75000000, guaranteed: 75000000, apy: 12500000, throughYear: 2028 },
    career: [
      { years: "2021–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2023 NL Ks leader" },
    ],
  },
  {
    id: "murphy",
    name: "Sean Murphy",
    number: 12,
    position: "C",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 31, experience: 7,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Walt Weiss said pre-game Apr 28 that Murphy will stay on his Triple-A Gwinnett rehab another 4-5 days for additional at-bats before being reevaluated. Caught Strider's third rehab start (Apr 26) and is up to 7 innings behind the dish. First-half-of-May Atlanta return still in play but no longer locked in.",
    form: 0,
    status: "il-60",
    injuryNote: "Right hip labral tear (Sep 2025 surgery). Rehab assignment continues at Triple-A Gwinnett — staying down another 4-5 days for at-bats before being reevaluated. First-half-of-May Atlanta return still possible.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33557.png",
    assignment: "rehab",
    contract: { years: 6, total: 73000000, guaranteed: 73000000, apy: 12166666, throughYear: 2028 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB · 2023 NL All-Star · Gold Glove" },
      { years: "2019–2022", team: "Oakland Athletics", type: "MLB" },
    ],
  },
  {
    id: "kim",
    name: "Ha-Seong Kim",
    number: 7,
    position: "SS",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇰🇷 South Korea", age: 30, experience: 5,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Officially began his major-league rehab assignment Tuesday (Apr 28) with the Double-A Columbus Clingstones — the first MLB rehab assignment in Clingstones franchise history. Walt Weiss said pre-game that Kim will need \"a couple of weeks\" of at-bats before the Braves consider promoting him; mid-May target for the Atlanta debut still holds.",
    form: 0,
    status: "il-60",
    injuryNote: "Torn tendon right middle finger (Jan 2026 surgery — slipped on ice in South Korea). Rehab assignment underway at Double-A Columbus (six-game homestand vs Montgomery opened Apr 28). \"A couple of weeks\" timetable per Weiss; mid-May Atlanta target.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4089862.png",
    assignment: "rehab",
    contract: { years: 2, total: 24000000, guaranteed: 24000000, apy: 12000000, throughYear: 2027 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2021–2025", team: "San Diego Padres", type: "MLB · Gold Glove" },
    ],
  },
  {
    id: "smith-shawver",
    name: "AJ Smith-Shawver",
    number: 60,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 23, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, w: null, l: null, games: null, starts: null },
    statNote: "Tommy John June 2025 — return window 2026 or 2027 season.",
    form: 0,
    status: "il-60",
    injuryNote: "Tommy John surgery (Jun 2025). Return: late 2026 or 2027.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4917640.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "waldrep",
    name: "Hurston Waldrep",
    number: 66,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 24, experience: 2,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, w: null, l: null, games: null, starts: null },
    statNote: "Set to throw his first bullpen session this week — Walt Weiss confirmed pre-game Apr 28. Targeted return remains June for game action.",
    form: 0,
    status: "il-60",
    injuryNote: "Right elbow inflammation; post-arthroscopic surgery Feb 23. First post-surgery bullpen session scheduled for this week (per Weiss, Apr 28). Targeted return: June.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4740117.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB · 2023 R1 pick" },
    ],
  },
  {
    id: "schwellenbach",
    name: "Spencer Schwellenbach",
    number: 56,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 26, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, w: null, l: null, games: null, starts: null },
    statNote: "Recovering from offseason arthroscopic elbow surgery.",
    form: 0,
    status: "il-60",
    injuryNote: "Arthroscopic elbow surgery. Targeted return: late June / July.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4424862.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "jimenez",
    name: "Joe Jiménez",
    number: 77,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: null,
    bats: "R", throws: "R",
    nationality: "🇵🇷 Puerto Rico", age: 31, experience: 9,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Knee surgery — no timetable.",
    form: 0,
    status: "il-60",
    injuryNote: "Left knee surgery. No timetable for return.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33760.png",
    assignment: "mlb",
    contract: { years: 3, total: 26000000, guaranteed: 26000000, apy: 8666666, throughYear: 2026 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB · 2018 AL All-Star" },
    ],
  },
  {
    id: "young",
    name: "Danny Young",
    number: 69,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: null,
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 30, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Transferred to 60-day IL Apr 11. Could return after the All-Star break.",
    form: 0,
    status: "il-60",
    injuryNote: "Tommy John (May 2025). Transferred to 60-day IL Apr 11.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40903.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
];

// ─── RSS FEEDS (news pipeline) ─────────────────────────────────────────────────
export const RSS_FEEDS = [
  {
    name: "MLB.com Braves",
    url: "https://www.mlb.com/braves/feeds/news/rss.xml",
    category: "official",
  },
  {
    name: "Battery Power",
    url: "https://www.batterypower.com/rss/index.xml",
    category: "fan",
  },
  {
    name: "AJC Braves",
    url: "https://www.ajc.com/arc/outboundfeeds/rss/section/sports/braves/",
    category: "major",
  },
  {
    name: "MLB Trade Rumors – Braves",
    url: "https://www.mlbtraderumors.com/atlanta-braves/feed",
    category: "major",
  },
  {
    name: "Talking Chop",
    url: "https://www.talkingchop.com/rss/index.xml",
    category: "fan",
  },
];

// ─── TEAM LOGOS (NL East + recent opponents) ────────────────────────────────────
export const TEAM_LOGOS = {
  ATL: "https://a.espncdn.com/i/teamlogos/mlb/500/atl.png",
  PHI: "https://a.espncdn.com/i/teamlogos/mlb/500/phi.png",
  NYM: "https://a.espncdn.com/i/teamlogos/mlb/500/nym.png",
  WSH: "https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png",
  MIA: "https://a.espncdn.com/i/teamlogos/mlb/500/mia.png",
  KC:  "https://a.espncdn.com/i/teamlogos/mlb/500/kc.png",
  LAD: "https://a.espncdn.com/i/teamlogos/mlb/500/lad.png",
  SD:  "https://a.espncdn.com/i/teamlogos/mlb/500/sd.png",
  NYY: "https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png",
  HOU: "https://a.espncdn.com/i/teamlogos/mlb/500/hou.png",
};

// ─── UPCOMING SCHEDULE ─────────────────────────────────────────────────────────
// The next ~5 scheduled games used by the rotation map / probable-pitchers strip.
// Skill maintains this each daily run: drop today's game once it moves to RESULTS,
// add a new tail entry. atlSP.id should match a PLAYERS entry so the avatar can
// render; use null for true TBAs. daysRest is calendar days since last MLB start.
export const UPCOMING_SCHEDULE = [
  {
    date: "2026-05-03",
    weekday: "Sun",
    time: "3:10 PM ET",
    opp: "COL",
    home: false,
    venue: "Coors Field",
    atlSP: { id: "strider", name: "Spencer Strider", record: null, era: null, daysRest: 7, hand: "R" },
    oppSP: { name: "Kyle Freeland", record: "1-2", era: 3.48, hand: "L" },
    note: "STRIDER'S 2026 MLB DEBUT · activated from 15-day IL today · first big-league outing since spring oblique strain · 18 K / 12.2 IP across 3 rehab starts at Gwinnett · 95.2 mph avg / 96.9 peak FB last time out",
  },
  {
    date: "2026-05-04",
    weekday: "Mon",
    time: "9:40 PM ET",
    opp: "SEA",
    home: false,
    venue: "T-Mobile Park",
    atlSP: { id: "perez-martin", name: "Martín Pérez", record: "2-1", era: 2.22, daysRest: 6, hand: "L" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Three-game series at Seattle opens · long road trip continues · Pérez lined up after his Apr 28 W vs DET",
  },
  {
    date: "2026-05-05",
    weekday: "Tue",
    time: "9:40 PM ET",
    opp: "SEA",
    home: false,
    venue: "T-Mobile Park",
    atlSP: { id: "ritchie", name: "JR Ritchie", record: "1-0", era: 2.92, daysRest: 6, hand: "R" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Ritchie's 3rd MLB start · ND vs DET on Apr 29 in his second outing",
  },
  {
    date: "2026-05-06",
    weekday: "Wed",
    time: "3:40 PM ET",
    opp: "SEA",
    home: false,
    venue: "T-Mobile Park",
    atlSP: { id: "elder", name: "Bryce Elder", record: "3-1", era: 1.88, daysRest: 6, hand: "R" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Day-game getaway · Elder's sub-1.90 ERA gets a Pacific NW test · cross-country road trip continues",
  },
  {
    date: "2026-05-08",
    weekday: "Fri",
    time: "7:10 PM ET",
    opp: "LAD",
    home: true,
    venue: "Truist Park",
    atlSP: { id: "sale", name: "Chris Sale", record: "6-1", era: 2.14, daysRest: 5, hand: "L" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Marquee homestand opener vs Dodgers after a Thu travel day · Sale lined up on his normal turn after the 11-K Coors gem",
  },
];

// ─── NEXT GAME ──────────────────────────────────────────────────────────────────
export const NEXT_GAME = {
  date: "2026-05-03",
  time: "3:10 PM ET",
  opp: "COL",
  home: false,
  venue: "Coors Field · Denver, CO",
  tv: "FanDuel Sports Network Southeast",
  probables: {
    atl: { pitcher: "Spencer Strider", record: "—", era: null },
    opp: { pitcher: "Kyle Freeland", record: "1-2", era: 3.48 },
  },
  note: "STRIDER'S 2026 MLB DEBUT — Atlanta (24-10, MLB-best record by 1.5 over LAD) closes the road series at altitude with the most-anticipated start of the year. Strider activated from the 15-day IL this morning after a spring oblique strain cost him the first month; three Triple-A Gwinnett rehab starts produced 12.2 IP / 18 K / 2 ER, FB peaking at 96.9 mph. Coors as the debut venue is bold — the team is comfortable enough with the stuff to risk it. Colorado counters with LHP Kyle Freeland (1-2, 3.48). Atlanta rides momentum from Saturday's 9-1 Sale-led blowout (7 IP / 1 ER / 11 K, MLB-leading 6th W) and Drake Baldwin's 4-RBI cycle-bid (2-run HR, 3 hits). Concerning note: Ronald Acuña Jr. left Saturday in the 2nd with left hamstring tightness; MRI pending. Iglesias eligible to be activated Tuesday May 5.",
};

// ─── RECENT RESULTS ─────────────────────────────────────────────────────────────
export const RESULTS = [
  { date: "2026-05-02", opp: "COL", home: false, atlScore: 9, oppScore: 1, result: "W", note: "SALE DOMINATES AT ALTITUDE, BALDWIN ALMOST CYCLES — Atlanta's MLB-best record climbs to 24-10 in a 9-1 rout at Coors. Chris Sale (W, 6-1) was masterful: 7 IP / 3 H / 1 ER / 11 K — MLB-leading 6th W and a Coors line that's almost unheard of. Drake Baldwin (3-for-4, 4 RBI) opened the scoring with a 2-run HR (#8) off COL LHP Brennan Bernardino (LP, 2-1) in the 1st, then doubled and singled — a triple short of the cycle. Olson #11 (now MLB co-leader) and Riley #4 added insurance. Lone scare: Ronald Acuña Jr. exited in the 2nd inning with left hamstring tightness after pulling up halfway down the line on a grounder; he walked off gingerly and will undergo an MRI. Atlanta now 14 of last 17, 7.5+ GM up on MIA in the NL East and best record in MLB by 1.5 over LAD." },
  { date: "2026-05-01", opp: "COL", home: false, atlScore: 8, oppScore: 6, result: "W", note: "INSTANT CLASSIC AT COORS — Atlanta erased a 6-0 deficit with EIGHT UNANSWERED runs, capped by Michael Harris II's pinch-hit 2-run HR off Tyler Kinley in the 9th. Tied for the franchise's largest comeback ever at Coors Field. Holmes got bullied by altitude (4 IP / 4 ER / 6 H, ND); Quintana matched zeros for COL through 4. The Braves scratched a run in the 7th, then exploded for 4 in the 8th — Mauricio Dubón's BASES-LOADED TRIPLE the dagger that tied it 6-6, with Olson's #10 HR fueling the cushion. Didier Fuentes (W, 1-0) went 2 scoreless out of the pen (5th–6th, 3 K). Pierce Johnson worked a clean 9th for his first save. Atlanta moves to 23-10 and 7.5 GM up on MIA. Pregame: Suárez and Payamps DFA'd; Stratton and Molina recalled/selected from Triple-A Gwinnett." },
  { date: "2026-04-30", opp: "DET", home: true,  atlScore: 2, oppScore: 5, result: "L", note: "Tigers avoid the sweep with a 4-run 8th. Bryce Elder (ND) was excellent: 6 IP / 6 H / 1 ER / 3 BB / 5 K, exiting with a 2-1 lead. Joel Payamps gave up Carpenter's leadoff triple to start the 8th and Vierling's tying double chased him; Aaron Bummer relieved, walked McGonigle, then Gleyber Torres's go-ahead sac fly made it 3-2. José Suárez (LP) walked Pérez and Hao-Yu Lee in the 9th, Yastrzemski misplayed Vierling's third hit for an error, and Dingler's double iced it at 5-2. Atlanta still takes the series 2-1; the 10-game ATL streak vs DET ends. Tigers finish April 14-13 and stay atop the AL Central at 16-16 on the trip." },
  { date: "2026-04-29", opp: "DET", home: true,  atlScore: 4, oppScore: 3, result: "W", note: "WALK-OFF — Matt Olson clubbed a 2-run, 397-ft HR (#9) into the Atlanta bullpen off ex-Brave Kenley Jansen on the 5th pitch of the AB, after Albies opened the 9th with a walk. Spoiled a dominant Tarik Skubal start (7 IP / 5 H / 2 ER / 0 BB / 7 K, 91 pitches) — Albies 2-run HR (#7) in the 1st was Atlanta's only damage off the AL Cy Young. JR Ritchie pitched into the 6th in his second MLB start (ND); a pickoff-throw error on McGonigle in the 2nd let DET tie it. Reynaldo López (W, 2-1) was the difference: 2 scoreless / 0 H / 2 K out of the pen in the 8th–9th. Tigers closer Jansen has now allowed walk-off HRs in back-to-back outings." },
  { date: "2026-04-28", opp: "DET", home: true,  atlScore: 5, oppScore: 2, result: "W", note: "Martín Pérez (W, 2-1) tossed 5 scoreless on 2 H / 4 BB / 5 K in the series opener vs the AL Central champs — first W over Detroit since Aug 25, 2019. Yastrzemski/Acuña hit back-to-back doubles in the 3rd, Acuña scored on Olson's sac fly for a 2-0 lead, and Albies smashed a 2-run HR (#6, 377 ft, 98.5 mph EV) off Tyler Holton in the 8th to put it away. DET RHP Casey Mize (LP, 2-2) left after 2.1 IP with right groin tightness. Atlanta improves to 21-9, tied with LAD for best in MLB." },
  { date: "2026-04-26", opp: "PHI", home: true,  atlScore: 6, oppScore: 2, result: "W", note: "Sale's 150th career W and a season-high 9 K across 6 shutout IP / 1 H on 88 pitches. Olson 3-run HR off Nola in the 1st (#9, 4th career off Nola), Eli White 2-run HR in the 2nd. Acuña 2-3, R, SB. Schwarber 2-run HR off the pen in the 8th avoided the shutout. ATL takes the series 2-1 — first MLB team to 20 wins; 10-2 in last 12. Pregame: Brian Snitker inducted into the Braves Hall of Fame." },
  { date: "2026-04-25", opp: "PHI", home: true,  atlScore: 5, oppScore: 8, result: "L", note: "10-inning walk-off L — Bryce Harper (4 RBI) lined a tiebreaking single in the 10th off José Suárez (LP); Marsh added a 2-run insurance knock. Elder solid (7 IP / 6 H / 3 R / 2 K / 1 BB) and left with a 4-3 lead before Dylan Lee gave up Schwarber's leadoff triple and Harper's tying sac fly in the 8th. Wheeler (5 IP / 2 R / 3 H / 6 K) looked sharp in his 2026 debut. Phillies' 10-game losing streak ends." },
  { date: "2026-04-24", opp: "PHI", home: true,  atlScore: 5, oppScore: 3, result: "W", note: "Pinch-hitter Michael Harris II (scratched pregame with quad tightness) hammered a 2-run go-ahead double off Painter in the 6th, scoring Smith and Dubón. Acuña 2-run HR; Holmes (W, 2-1) 6 IP, allowed Trea Turner & Bryce Harper HRs. Phillies' 10th straight loss." },
  { date: "2026-04-23", opp: "WSH", home: false, atlScore: 7, oppScore: 2, result: "W", note: "JR Ritchie dazzles in MLB debut — 7 IP / 2 ER / 7 K on 89 pitches after allowing a HR on his first-ever big-league pitch. Albies HR + 4 RBI breaks a 2-2 tie with 4-run 7th. 8th W in 9; 5th straight series win." },
  { date: "2026-04-22", opp: "WSH", home: false, atlScore: 8, oppScore: 6, result: "W", note: "Rally from 4-1 down — Harris 2 HR / 3 RBI, Olson 3-run HR (#8), Baldwin HR, Acuña tying sac fly. Fuentes' 3 IP spot start (4 ER) bailed out by the offense." },
];

// ─── NL EAST STANDINGS ──────────────────────────────────────────────────────────
export const NL_EAST_STANDINGS = [
  { team: "ATL", name: "Atlanta Braves",         w: 24, l: 10, pct: .706, gb: 0,    streak: "W2" },
  { team: "MIA", name: "Miami Marlins",          w: 15, l: 18, pct: .455, gb: 8.5,  streak: "L2" },
  { team: "WSH", name: "Washington Nationals",   w: 15, l: 19, pct: .441, gb: 9,    streak: "L2" },
  { team: "PHI", name: "Philadelphia Phillies",  w: 14, l: 19, pct: .424, gb: 9.5,  streak: "W3" },
  { team: "NYM", name: "New York Mets",          w: 11, l: 22, pct: .333, gb: 12.5, streak: "L2" },
];

// ─── NEWS DIGEST — the recency-biased summary the skill refreshes daily ──────────
export const NEWS_DIGEST = {
  generatedAt: "2026-05-03T09:00:00-04:00",
  summary:
    "STRIDER DAY at altitude — Atlanta sits 24-10 (.706), best record in MLB by 1.5 over the Dodgers and 8.5 GM up on second-place MIA in the NL East, and gets its biggest reinforcement of the year today: Spencer Strider has been activated from the 15-day IL and will make his 2026 MLB debut in the Coors Field series finale (3:10 PM ET) opposite COL LHP Kyle Freeland. Three Triple-A Gwinnett rehab starts produced 12.2 IP / 18 K / 2 ER, with the FB sitting 95.2 mph avg / 96.9 peak. Atlanta heads in on a 2-game roll: Saturday's 9-1 rout was a Chris Sale clinic — 7 IP / 3 H / 1 ER / 11 K for his MLB-leading 6th W, with Drake Baldwin (3-for-4, 2-run HR #8, 4 RBI, triple short of the cycle), Matt Olson (HR #11, MLB co-leader) and Austin Riley (HR #4) doing the damage. ONE DARK CLOUD: Ronald Acuña Jr. exited in the 2nd inning Saturday with left hamstring tightness after pulling up halfway down the line on a grounder; he walked off gingerly and an MRI is pending — extent unknown until later Sunday. Friday's prequel was a franchise-tying largest comeback at Coors (down 6-0, won 8-6 on Harris II's pinch-hit 9th-inning HR). Roster: Iglesias (shoulder) eligible to be activated Tuesday May 5; Murphy continues his Triple-A Gwinnett rehab (4-5 more days for at-bats); Kim is mid-rehab at Double-A Columbus targeting mid-May; Waldrep throwing his first post-surgery bullpen this week (June return); Schwellenbach (elbow) still not throwing. Around the division: MIA 15-18 (8.5 GB, L2), WSH 15-19 (9 GB, L2), PHI 14-19 (9.5 GB, W3), NYM 11-22 (12.5 GB, L2). Atlanta is now 15 of last 18 and the cushion has only grown.",
  keyTopics: [
    { category: "rotation",    title: "STRIDER'S 2026 MLB DEBUT — today, 3:10 PM at Coors",                  detail: "Spencer Strider was activated from the 15-day IL this morning and starts the series finale at altitude vs COL LHP Kyle Freeland (1-2, 3.48). First big-league outing since the spring oblique strain. Three Triple-A Gwinnett rehab starts produced 12.2 IP / 18 K / 2 ER, including an Apr 26 dress rehearsal of 5 IP / 4 H / 2 ER / 2 BB / 7 K on 82 pitches with 17 swings-and-misses (FB 95.2 mph avg / 96.9 peak). Coors as the debut venue is a bold call by Walt Weiss; the team is comfortable enough with the stuff to risk it." },
    { category: "result",      title: "Sale dominates Coors: 9-1 rout, 11 K, MLB-leading 6th W",             detail: "Chris Sale (W, 6-1) carved up the Rockies for 7 IP / 3 H / 1 ER / 11 K — a Coors line that's almost unheard of for a left-hander. Season ERA falls to 2.14, WHIP to 0.83, and his 49 K leads the NL. Brennan Bernardino (LP, 2-1) was hit hard early and pulled after 2/3 IP. Atlanta improves to 24-10, MLB-best by 1.5 over LAD." },
    { category: "injury",      title: "ACUÑA JR. EXITS WITH HAMSTRING TIGHTNESS — MRI PENDING",              detail: "Ronald Acuña Jr. left Saturday's game in the 2nd inning after pulling up halfway down the line on a ground ball, grabbing at his left hamstring. He was examined on the field, walked gingerly off, and was replaced by Eli White. Walt Weiss said Acuña will undergo an MRI; clarity expected late Sunday or after. The 28-year-old had played in all 34 ATL games this season after being limited to 144 G across 2024-25 (post-ACL). Concerning development." },
    { category: "milestone",   title: "Baldwin nearly cycles: 4 RBI, 2-run HR (#8), 3 hits",                 detail: "Drake Baldwin matched his single-game career high with 3 hits and finished a triple short of the cycle in Saturday's 9-1 W. The 2-run HR off Bernardino in the 1st (#8 of the year) opened the scoring; he's now slashing .322/.395/.550 with 8 HR / 29 RBI through 33 G as the everyday catcher with Murphy still on rehab. Bat is firmly in middle-of-the-order mode." },
    { category: "milestone",   title: "Olson #11 — MLB HR co-leader, 1.000 OPS",                              detail: "Matt Olson went deep for his 11th of the season Saturday at Coors, sliding into a tie for the MLB lead. He's now .298/.371/.629 with a 1.000 OPS, 31 RBI through 34 G — a top-three hitter in the sport by OPS. Three straight games with a HR (Friday #10 off Kinley, Wednesday's walk-off vs DET, Saturday at altitude)." },
    { category: "milestone",   title: "Riley snaps the slump: HR #4 in the rout",                            detail: "Austin Riley's first HR in two weeks, a solo shot at Coors Saturday (#4), is the bat-speed sign Atlanta has been waiting for. Slash creeps up to .194/.278/.333 — still well below career marks — but the power is showing signs of life on the West Coast trip. 18 RBI through 33 G; the bat needs the road swing to catalyze a turnaround." },
    { category: "result",      title: "Friday: largest-ever ATL comeback at Coors (8-6)",                    detail: "Down 6-0 after four (Holmes bullied by altitude: 4 IP / 4 ER, ND), the Braves ripped off EIGHT UNANSWERED. Mauricio Dubón's bases-loaded triple in a 4-run 8th tied it 6-6; Olson's #10 HR added air; Michael Harris II then pinch-hit a 2-run go-ahead HR off Tyler Kinley in the 9th. Didier Fuentes (W, 1-0) was the bridge with 2 scoreless out of the pen; Pierce Johnson worked a clean 9th for his first save. Tied for the franchise's largest comeback at Coors Field." },
    { category: "transaction", title: "Suárez, Payamps DFA'd Friday; Stratton, Molina up",                   detail: "Pregame Friday Atlanta DFA'd LHP José Suárez (28, 6.61 ERA across 8 G / 16.1 IP, out of options) and RHP Joel Payamps (31, 8.22 ERA across 12 G / 7.2 IP, out of options). RHP Hunter Stratton was recalled from Triple-A Gwinnett — back from the Achilles/patellar-tendon injury that ended his 2025 — and RHP Anthony Molina (a Dec 2025 waiver claim from COL, four-pitch strike-thrower) had his contract selected." },
    { category: "injury",      title: "Iglesias eligible to be activated Tuesday May 5",                     detail: "Closer Raisel Iglesias has resumed throwing and the right shoulder inflammation has subsided. Tuesday May 5 is the first eligible date and the Braves remain optimistic about a minimum-IL stint. Robert Suarez has handled the closer role spotlessly (3 SV, 0.71 ERA) since taking over Apr 22." },
    { category: "injury",      title: "Murphy stays at Gwinnett — needs more reps",                          detail: "Weiss said pre-game Apr 28 that Murphy (right hip labral surgery, Sep 2025) will spend another 4-5 days on his Triple-A rehab assignment to bank at-bats. He's been hitless in early plate appearances and the team wants more swings before activation. First-half-of-May Atlanta return still in play; Drake Baldwin continues to start most games behind the dish." },
    { category: "injury",      title: "Kim continues Double-A Columbus rehab; mid-May target",                detail: "Ha-Seong Kim is in the middle of his Columbus Clingstones rehab assignment — the first MLB rehab in franchise history. Weiss reiterated Kim will need \"a couple of weeks\" of game action before promotion; mid-May Atlanta target stands. Right middle finger torn tendon (Jan 2026 surgery) was the original injury." },
    { category: "lineup",      title: "Eli White next man up if Acuña lands on the IL",                       detail: "Eli White, who replaced Acuña in right Saturday, is the most likely beneficiary of any IL stint — he has the only true RF backup profile on the roster, and he's already homered twice in spot duty (Apr 26 vs PHI, Apr 21 at WSH). Yastrzemski could also slide over from LF/CF in a pinch. The depth is there to absorb a short-term loss." },
    { category: "standings",   title: "NL East: ATL +8.5 over MIA; PHI on a 3-game streak",                   detail: "ATL 24-10 (.706); MIA 15-18 (8.5 GB, L2); WSH 15-19 (9 GB, L2); PHI 14-19 (9.5 GB, W3) keeps inching back; NYM 11-22 (12.5 GB, L2) — the slide continues. Atlanta now also leads MLB by 1.5 over the Dodgers; the divisional cushion grew again Saturday." },
    { category: "narrative",   title: "Cavalry incoming: Strider today, Iglesias Tuesday, Murphy soon",       detail: "Atlanta's reinforcement timeline is now defined. Strider debuts today, Iglesias is throwing and could be activated as early as Tuesday, Murphy is days from his Gwinnett wrap-up, and Kim is targeting mid-May. The May 5 Braves could look meaningfully better than the 24-10 group that just won three of four to open the road trip — assuming Acuña's hamstring news comes back clean." },
  ],
  sources: [
    "MLB.com", "ESPN", "AJC", "Atlanta News First", "Battery Power", "MLB Trade Rumors", "CBS Sports", "Yahoo Sports", "Sports Illustrated", "Baseball-Reference", "Heavy.com", "Fox Sports", "RotoWire", "FanDuel", "ClutchPoints", "Field Level Media", "Bleacher Nation", "AP", "Washington Post", "Athlon Sports",
  ],
};
