// ─── Atlanta Braves Player Data (2026 Season · Updated May 8, 2026) ──────────
// Single source of truth for roster, games, standings, digest, and RSS feeds.
// Season context: 26-12 (.684) — still MLB-best, leading the NL East by 9.0
// games over a logjam of three teams (PHI/MIA/WSH all 17-21) after Thursday's
// results elsewhere. TONIGHT IS THE MARQUEE OPENER: Chris Sale (6-1, 2.14,
// NL-leading 49 K) takes the ball at DODGER STADIUM (10:10 PM ET, FanDuel
// Sports Network Southeast / SportsNet LA) opposite RHP Emmet Sheehan, who's
// coming off a 4-ER (2 HR) loss in St. Louis with 8 K and 0 BB. The defending
// champ Dodgers (24-15) host Atlanta for three at Chavez Ravine after Atlanta
// wrapped a 3-3 west-coast first leg in Seattle (lost the rubber match 3-1
// to Bryan Woo's 9-K masterclass on Wed). Acuña Jr. remains on the 10-day IL
// (Grade 1 left hamstring, mid-to-late-May target); Harris II continues DH-only
// for the back-half of his ~7-day quad nursing window; Murphy still easing back
// in; Iglesias secure as closer (6 SV in 6 chances); Dodd's Triple-A Gwinnett
// rehab outing went well but the Braves have NOT activated him yet — he could
// be reinstated this weekend. Olson (NL-leading 13 HR, .302/.372/.647, 1.019
// OPS, 33 RBI) and Albies (.322, 8 HR, 23 RBI, .915 OPS) drive the offense.
// Today is a GAME DAY — first pitch 7:10 PT / 10:10 PM ET.
//
// Statuses: "active" | "day-to-day" | "questionable" | "il-10" | "il-15" | "il-60" | "suspended" | "departed"
// Assignments: "mlb" | "aaa" | "aa" | "rehab"  (org-level location, orthogonal to injury status)
//   mlb   = on the 26/40-man active roster with the big club
//   aaa   = optioned or stashed at Triple-A Gwinnett (recall candidate)
//   aa    = lower-level depth (rare; used for high-profile prospects only)
//   rehab = on IL + currently on a minor-league rehab assignment
// injuryNote: short description shown on card when not active

export const PLAYERS = [
  // ── STARTING LINEUP ─────────────────────────────────────────────────────────
  {
    id: "acuna",
    name: "Ronald Acuña Jr.",
    number: 13,
    position: "RF",
    positionGroup: "batter",
    lineupSpot: 1,
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 28, experience: 8,
    stats: { avg: .238, obp: .349, slg: .368, ops: .717, hr: 2, rbi: 9, sb: 6, bb: 19, so: 32, games: 34 },
    statNote: "ON THE 10-DAY IL (May 3) — POSSIBLE WED RETURN — MRI confirmed a Grade 1 left hamstring strain. Manager Walt Weiss said pre-game Friday Acuña has a 'very good chance' to be back in the lineup Wednesday May 13 — the first day he'd be eligible to come off the 10-day IL. Acuña was seen doing on-field agility work Friday at Dodger Stadium and 'has a few boxes left to check.' He'd appeared in all 34 ATL games this season after being limited to 144 G across 2024-25 (post-ACL). Apr 24 2-run HR off Painter remains his last bomb.",
    form: 0,
    status: "il-10",
    injuryNote: "Grade 1 left hamstring strain (suffered in 2nd inning of 9-1 W at Coors, May 2). Placed on 10-day IL May 3, retroactive. Doing on-field agility work in LA Friday; Weiss targeting Wednesday May 13 (first IL-eligible day) for a possible activation vs WSH. Eli White / Bairon Velandia / Jorge Mateo split RF reps in his absence.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/36185.png",
    assignment: "mlb",
    contract: { years: 8, total: 100000000, guaranteed: 100000000, apy: 12500000, throughYear: 2028 },
    career: [
      { years: "2018–", team: "Atlanta Braves", type: "MLB · 2023 NL MVP · 4x All-Star" },
    ],
  },
  {
    id: "olson",
    name: "Matt Olson",
    number: 28,
    position: "1B",
    positionGroup: "batter",
    lineupSpot: 2,
    bats: "L", throws: "R",
    nationality: "🇺🇸 USA", age: 32, experience: 10,
    stats: { avg: .295, obp: .366, slg: .631, ops: .997, hr: 13, rbi: 33, sb: 0, bb: 16, so: 39, games: 38, doubles: 3 },
    statNote: "QUIET NIGHT VS SHEEHAN AT DODGER STADIUM — Olson went hitless in the 3-1 L Friday, finally cooling against the LAD lefty-killing pen (Vesia, Hurt, Klein, Stewart, Scott). Still NL-leading with 13 HR / 33 RBI / .997 OPS / .295/.366/.631 through 38 G. The 9th-inning go-ahead bomb in Seattle Tuesday (#13, off Andrés Muñoz) and Monday's 300th-career-HR night (off Logan Gilbert) remain the centerpieces of his May. Saturday's matchup vs Roki Sasaki at Chavez Ravine sets up a bounce-back spot.",
    form: 9.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/32767.png",
    assignment: "mlb",
    contract: { years: 8, total: 168000000, guaranteed: 168000000, apy: 21000000, throughYear: 2029 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2023 HR title (54)" },
      { years: "2016–2021", team: "Oakland Athletics", type: "MLB" },
    ],
  },
  {
    id: "riley",
    name: "Austin Riley",
    number: 27,
    position: "3B",
    positionGroup: "batter",
    lineupSpot: 3,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 29, experience: 8,
    stats: { avg: .200, obp: .283, slg: .344, ops: .627, hr: 5, rbi: 20, sb: 2, bb: 12, so: 37, games: 37 },
    statNote: "PROVIDED ATL'S ONLY RUN AT DODGER STADIUM FRIDAY — Riley's 2nd-inning RBI single (off Sheehan, scoring Albies) gave Atlanta its lone tally in the 3-1 L. Sheehan immediately responded with consecutive K's to limit the damage. Still grinding at .200/.283/.344 (.627 OPS), 5 HR / 20 RBI through 37 G. The bat is showing slow life — the May 5 / May 7 walks and a clean RBI single Friday point the right direction even if the average hasn't moved.",
    form: 8.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/34982.png",
    assignment: "mlb",
    contract: { years: 10, total: 212000000, guaranteed: 212000000, apy: 21200000, throughYear: 2032 },
    career: [
      { years: "2019–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2x Silver Slugger" },
    ],
  },
  {
    id: "ozuna",
    name: "Marcell Ozuna",
    number: 20,
    position: "DH",
    positionGroup: "batter",
    lineupSpot: 4,
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 35, experience: 13,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Left Braves in FA before 2026 — retained in data as historical reference only. See Baldwin/Yastrzemski for current DH reps.",
    form: 0,
    status: "departed",
    injuryNote: "Signed elsewhere in FA. Not on 2026 Braves roster.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/30205.png",
    assignment: "mlb",
    contract: null,
    career: [
      { years: "2020–2025", team: "Atlanta Braves", type: "MLB · 2023 WS · 2x All-Star" },
    ],
  },
  {
    id: "albies",
    name: "Ozzie Albies",
    number: 1,
    position: "2B",
    positionGroup: "batter",
    lineupSpot: 5,
    bats: "S", throws: "R",
    nationality: "🇨🇼 Curaçao", age: 29, experience: 9,
    stats: { avg: .313, obp: .358, slg: .533, ops: .891, hr: 8, rbi: 23, sb: 0, bb: 9, so: 20, games: 37, wOBA: .315, iso: .160 },
    statNote: "DREW THE WALK AHEAD OF RILEY'S RBI SINGLE FRIDAY — Albies came around to score Atlanta's only run in the 3-1 L at Dodger Stadium after reaching against Sheehan. Slash holds at .313/.358/.533 (.891 OPS), 8 HR / 23 RBI through 37 G — still the steadiest top-of-order presence with Acuña sidelined. Saturday's Strider-Sasaki middle game lines up nicely for the Braves switch-hitter at sea level.",
    form: 9.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33783.png",
    assignment: "mlb",
    contract: { years: 7, total: 35000000, guaranteed: 35000000, apy: 5000000, throughYear: 2027 },
    career: [
      { years: "2017–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2021 WS champ" },
    ],
  },
  {
    id: "harris",
    name: "Michael Harris II",
    number: 23,
    position: "CF",
    positionGroup: "batter",
    lineupSpot: 6,
    bats: "L", throws: "R",
    nationality: "🇺🇸 USA", age: 25, experience: 5,
    stats: { avg: .345, obp: .376, slg: .578, ops: .954, hr: 7, rbi: 22, sb: 2, bb: 6, so: 18, games: 32, wrcPlus: null },
    statNote: "BACK IN CF AND 4-FOR-4 BATTING CLEANUP AT DODGER STADIUM — Harris was the lone bright spot in the 3-1 L Friday, going 4-for-4 with the quad healthy enough to handle CF after a week of DH-only usage. Hit cleanup for just the 10th time in his career. Slash now .345/.376/.578 (.954 OPS), 7 HR / 22 RBI in 32 G — back atop the team in average and OPS as Olson cooled. Quad is looking like a non-issue going into the rest of the LAD weekend.",
    form: 9.8,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/42470.png",
    assignment: "mlb",
    contract: { years: 8, total: 72000000, guaranteed: 72000000, apy: 9000000, throughYear: 2030 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 2022 NL ROY · Gold Glove" },
    ],
  },
  {
    id: "baldwin",
    name: "Drake Baldwin",
    number: 55,
    position: "C",
    positionGroup: "batter",
    lineupSpot: 7,
    bats: "L", throws: "R",
    nationality: "🇺🇸 USA", age: 25, experience: 2,
    stats: { avg: .315, obp: .388, slg: .547, ops: .935, hr: 9, rbi: 30, sb: 1, bb: 14, so: 31, games: 35 },
    statNote: "BACK BEHIND THE DISH AS MURPHY EASES IN — Baldwin caught Elder's 9-K Tuesday gem and went 0-for-3, dropping the line to .315/.388/.547 (.935 OPS), 9 HR / 30 RBI through 35 G. Monday's leadoff HR (#9) off Gilbert is still the mark of the series. With Murphy back from the 60-day IL but on the bench Wednesday after going 0-for-3 Monday, Baldwin remains the primary catcher of a true tandem rather than a backup-now arrangement.",
    form: 9.3,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4810190.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB · 3rd-round 2022 draft (Missouri State)" },
    ],
  },
  {
    id: "profar",
    name: "Jurickson Profar",
    number: 7,
    position: "LF",
    positionGroup: "batter",
    lineupSpot: 8,
    bats: "S", throws: "R",
    nationality: "🇨🇼 Curaçao", age: 33, experience: 14,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Everyday LF in the post-Ozuna outfield rotation.",
    form: 6.9,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/31117.png",
    assignment: "mlb",
    contract: { years: 3, total: 42000000, guaranteed: 42000000, apy: 14000000, throughYear: 2027 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB · 2024 NL All-Star" },
      { years: "2012–2024", team: "Various (TEX, OAK, COL, SD)", type: "MLB" },
    ],
  },
  {
    id: "allen",
    name: "Nick Allen",
    number: 14,
    position: "SS",
    positionGroup: "batter",
    lineupSpot: 9,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 27, experience: 4,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Sharing SS reps with Dubón while Kim rehabs finger tendon. Defense-first profile.",
    form: 6.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40338.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB" },
      { years: "2022–2024", team: "Oakland Athletics", type: "MLB" },
    ],
  },
  {
    id: "yastrzemski",
    name: "Mike Yastrzemski",
    number: 5,
    position: "RF",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 35, experience: 8,
    stats: { avg: .209, obp: .280, slg: .275, ops: .555, hr: 0, rbi: 6, sb: 1, bb: 8, so: 25, games: 29 },
    statNote: "Offseason FA signing struggling out of the gate — .209/.280/.275, no HRs through 29 games. The error on Vierling's bullet through the LF gap on Apr 30 added the dagger run in the 5-2 L. Veteran platoon-piece role still intact while the bat looks for traction.",
    form: 5.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33341.png",
    assignment: "mlb",
    contract: { years: 1, total: 7000000, guaranteed: 7000000, apy: 7000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2019–2025", team: "San Francisco Giants", type: "MLB · 2021 NL All-Star" },
    ],
  },
  {
    id: "dubon",
    name: "Mauricio Dubón",
    number: 2,
    position: "UT",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇭🇳 Honduras", age: 31, experience: 8,
    stats: { avg: .283, obp: .332, slg: .455, ops: .787, hr: 2, rbi: 18, sb: 0, bb: 6, so: 20, games: 31, triples: 1 },
    statNote: "BASES-LOADED TRIPLE in the 8th at Coors Friday — the swing that finished erasing the 6-run hole and tied it 6-6 before Harris's 9th-inning HR sealed it. 2-for-5, 3 RBI on the night. Primary SS while Kim rehabs; rotates through 2B/LF/CF as needed. Now .283/.332/.455 with 18 RBI through 31 games.",
    form: 8.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/35304.png",
    assignment: "mlb",
    contract: { years: 2, total: 8500000, guaranteed: 8500000, apy: 4250000, throughYear: 2027 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2022–2025", team: "Houston Astros", type: "MLB · 2022 & 2023 WS champ" },
    ],
  },
  {
    id: "heim",
    name: "Jonah Heim",
    number: 28,
    position: "C",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "S", throws: "R",
    nationality: "🇺🇸 USA", age: 30, experience: 6,
    stats: { avg: .244, obp: .293, slg: .415, ops: .708, hr: 2, rbi: 9, sb: 0, bb: 4, so: 12, games: 12 },
    statNote: "DFA'd 24 HOURS AFTER A CAREER-HIGH 5 RBI — Heim was designated for assignment Monday May 4 when Sean Murphy was reinstated from the IL, then traded to the Athletics for cash considerations Tuesday May 5. The numbers tell the brutal story: a 5-RBI Sunday at Coors (#2 HR off Quintana, bases-loaded sac fly, 9th-inning 2-run double) didn't save him — Atlanta committed to a Baldwin-Murphy catching tandem the moment Murphy passed his rehab check. Final Atlanta line: .244/.293/.415, 2 HR / 9 RBI in 12 G. Off to Sacramento.",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd May 4, 2026 — traded to the Athletics for cash on May 5. No longer on the Braves 40-man roster.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33842.png",
    assignment: "mlb",
    contract: { years: 1, total: 1250000, guaranteed: 1250000, apy: 1250000, throughYear: 2026 },
    career: [
      { years: "2026", team: "Atlanta Braves", type: "MLB · 12 G" },
      { years: "2020–2025", team: "Texas Rangers", type: "MLB · 2023 WS champ · 2023 AL All-Star · Gold Glove" },
    ],
  },
  {
    id: "mateo",
    name: "Jorge Mateo",
    number: 3,
    position: "UT",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 30, experience: 5,
    stats: { avg: .286, obp: .318, slg: .476, ops: .794, hr: 2, rbi: 5, sb: 3, bb: 2, so: 10, games: 16, runs: 12, doubles: 2 },
    statNote: "2-RUN HR (#2) off Kyle Freeland in the 2nd of Sunday's 11-6 W — back-to-back with Jonah Heim's 420-ft blast on the same Quintana curve set. Speed/defense bench-piece signing has been a real asset behind Dubón at SS while Kim rehabs: .286/.318/.476 with 12 R / 5 RBI / 3 SB across 16 G. Plays every OF spot too.",
    form: 8.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33832.png",
    assignment: "mlb",
    contract: { years: 1, total: 1000000, guaranteed: 1000000, apy: 1000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2022–2025", team: "Baltimore Orioles", type: "MLB · 2023 ALDS run" },
      { years: "2021–2022", team: "San Diego Padres", type: "MLB" },
    ],
  },
  {
    id: "jarvis",
    name: "Jim Jarvis",
    number: 5,
    position: "UT",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 25, experience: 0,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "MLB DEBUT MAY 6 — Atlanta selected Jarvis from Triple-A Gwinnett (Azocar DFA'd in the corresponding move) and slotted him in at SS batting 9th to give Mateo a day off. The 25-year-old Alabama product was an 11th-round 2023 Tigers pick before being traded to Atlanta at the 2025 deadline (for Rafael Montero). He was raking at Gwinnett: .305/.418/.445 with 4 HR / 15 SB across 33 G — and projects as a versatile utility infielder (SS/2B/3B) rather than a one-spot regular.",
    form: 7.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5205951.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · debut May 6, 2026" },
      { years: "2025", team: "Atlanta org", type: "Acquired from DET 7/30/25 in Rafael Montero trade" },
      { years: "2023–2025", team: "Detroit Tigers org", type: "11th round, 2023 (Alabama)" },
    ],
  },
  {
    id: "azocar",
    name: "José Azocar",
    number: 17,
    position: "OF",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 30, experience: 5,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "DFA'd MAY 6 — Atlanta designated Azocar for assignment to clear the spot for IF Jim Jarvis's MLB debut. Just three days after being selected from Triple-A Gwinnett (May 3) to fill Acuña's roster spot, the speed/defense fourth-outfielder is on the wire. Likely outcome: outright to Triple-A within 5 days, possibly traded for cash.",
    form: 6.0,
    status: "departed",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/35058.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2025", team: "New York Mets", type: "MLB" },
      { years: "2022–2024", team: "San Diego Padres", type: "MLB · debut 2022" },
    ],
  },

  // ── STARTING ROTATION ───────────────────────────────────────────────────────
  {
    id: "sale",
    name: "Chris Sale",
    number: 51,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 1,
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 37, experience: 15,
    stats: { era: 2.20, whip: 0.82, ip: 49.0, k: 56, bb: 9, hr: null, w: 6, l: 2, games: 8, starts: 8 },
    statNote: "TOUGH-LUCK L AT CHAVEZ RAVINE FRIDAY (6-2) — Sale was excellent in defeat: 7 IP / 5 H / 3 R / 2 ER / 7 K / 0 BB at Dodger Stadium, but ATL managed only one run on six hits off Sheehan and the LAD pen. Sheehan struck out seven across 4.2 IP and the bullpen (Vesia W, Hurt, Klein, Stewart, Tanner Scott SV) shut Atlanta down. Freeman's 6th-inning 413-ft leadoff HR (his 100th as a Dodger) was the dagger off Sale; Ohtani's 2-out RBI single in the 5th — after a Rojas error — gave LAD the lead. ATL's 8th straight L at Dodger Stadium. Season line: 2.20 ERA / 0.82 WHIP / NL-leading 56 K across 8 starts.",
    form: 9.7,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/30948.png",
    assignment: "mlb",
    contract: { years: 2, total: 54000000, guaranteed: 38000000, apy: 27000000, throughYear: 2027 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB · 2024 NL Cy Young" },
      { years: "2016–2023", team: "Boston Red Sox", type: "MLB · 2018 WS champ" },
      { years: "2010–2016", team: "Chicago White Sox", type: "MLB · 7x All-Star" },
    ],
  },
  {
    id: "lopez",
    name: "Reynaldo López",
    number: 40,
    position: "RP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 32, experience: 10,
    stats: { era: 3.42, whip: 1.31, ip: 23.2, k: 22, bb: 11, hr: null, w: 2, l: 1, games: 6, starts: 5 },
    statNote: "Picked up the W (now 2-1, ERA down to 3.27) in Wednesday's 4-3 walk-off over DET — 2 scoreless / 0 H / 2 K out of the bullpen in the 8th and 9th, setting up Olson's walk-off blast. Second pen outing of the Walt Weiss reset (Apr 27) and a clear sign the slider work is taking. Weiss has said López projects back to the rotation once the mechanical reset is done.",
    form: 7.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33860.png",
    assignment: "mlb",
    contract: { years: 3, total: 30000000, guaranteed: 30000000, apy: 10000000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB · 2024 NL All-Star" },
      { years: "2018–2023", team: "Chicago White Sox", type: "MLB" },
    ],
  },
  {
    id: "holmes",
    name: "Grant Holmes",
    number: 58,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 3,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 30, experience: 3,
    stats: { era: 4.50, whip: 1.40, ip: 36.1, k: 27, bb: 17, w: 2, l: 1, games: 7, starts: 7 },
    statNote: "Got bullied by altitude Friday — 4 IP / 6 H / 4 ER / 3 BB / 2 K, ND in Atlanta's 8-6 comeback W. Quintana matched zeroes through 4 (Holmes left trailing 4-0); the Braves' bullpen and offense bailed him out. ERA up to 4.50 across 7 starts, but the rotation depth absorbs the bad start. Apr 24 W vs PHI (6 IP, 2 ER) still the line-of-the-month for him.",
    form: 7.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33840.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "elder",
    name: "Bryce Elder",
    number: 55,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 4,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 27, experience: 4,
    stats: { era: 2.02, whip: 1.06, ip: 49.0, k: 45, bb: 16, w: 3, l: 1, games: 8, starts: 8 },
    statNote: "9-K MASTERPIECE IN SEATTLE — Tuesday: 6 IP / 2 H / 2 ER / 3 BB / 9 K (season-high K total), 78 pitches / 51 strikes, ND in Atlanta's 3-2 W after the offense was held in check by Kirby. The two earned came on a Cal Raleigh solo HR; otherwise Elder twirled a chess match against Seattle's contact-heavy lineup. ERA ticks up to 2.02 across 8 starts, but the strike-throwing version is the rotation's most consistent piece behind Sale.",
    form: 8.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4301067.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 2023 NL All-Star" },
    ],
  },
  {
    id: "suarez-jose",
    name: "José Suárez",
    number: 49,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 5,
    bats: "L", throws: "L",
    nationality: "🇻🇪 Venezuela", age: 28, experience: 7,
    stats: { era: 6.61, whip: 2.08, ip: 16.1, k: 21, bb: 12, w: 0, l: 1, games: 8, starts: 1 },
    statNote: "Designated for assignment May 1 in the corresponding move when Hunter Stratton was recalled. Out of minor-league options, 6.61 ERA across 8 G / 16.1 IP. Took the LP in both the Apr 25 (10) walk-off vs PHI and the Apr 30 5-2 finale vs DET (walked two in the 9th).",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd May 1, 2026 — off the 40-man.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40981.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2019–2025", team: "Los Angeles Angels", type: "MLB" },
    ],
  },
  {
    id: "perez-martin",
    name: "Martín Pérez",
    number: 54,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 6,
    bats: "L", throws: "L",
    nationality: "🇻🇪 Venezuela", age: 35, experience: 14,
    stats: { era: 2.38, whip: 1.03, ip: 34.0, k: 24, bb: 12, w: 2, l: 2, games: 7, starts: 5 },
    statNote: "PRESSED INTO SERVICE WEDNESDAY, TOUGH-LUCK L (2-2) — Pérez took the rubber-match start in Seattle on short turn (5 days) and was solid: 5.2 IP / 5 H / 2 ER / 3 BB / 5 K, but Atlanta managed just 4 hits and 1 run for him. Cole Young's RBI double in the 3rd off a 6-4-3 DP set the tone; Julio Rodríguez's solo HR in the 6th was the killer. ERA up slightly to 2.38; pen-day-style usage may continue if Strider's next outing slots in around the LAD series.",
    form: 7.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/31098.png",
    assignment: "mlb",
    contract: { years: 1, total: 2000000, guaranteed: 0, apy: 2000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · 2022 AL All-Star" },
      { years: "2012–2025", team: "Various (TEX, BOS, MIN, PIT, CHW)", type: "MLB" },
    ],
  },
  {
    id: "ritchie",
    name: "JR Ritchie",
    number: 48,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 7,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 22, experience: 0,
    stats: { era: 3.63, whip: 1.50, ip: 17.1, k: 13, bb: 12, w: 1, l: 0, games: 3, starts: 3 },
    statNote: "HOMECOMING WITH GROWING PAINS — Seattle native Ritchie battled command in front of family at T-Mobile Park: 5 IP / 4 H / 3 ER / 6 BB / 2 K, ND in Atlanta's 5-4 L. Threw just 47 of 93 pitches for strikes; opened the 6th by walking the first two batters before serving up a 3-run HR to Luke Raley. Crawford's 2-run go-ahead HR off the bullpen in the bottom of the 6th flipped the 4-0 lead. ERA up to 3.63, WHIP 1.50 over 17.1 IP. Debut Apr 23 at WSH (7 IP / 2 ER / 7 K) is still the line-of-the-month for him.",
    form: 7.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5080757.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · MLB debut Apr 23, 2026" },
    ],
  },

  // ── BULLPEN ─────────────────────────────────────────────────────────────────
  {
    id: "iglesias",
    name: "Raisel Iglesias",
    number: 26,
    position: "CP",
    positionGroup: "pitcher",
    bullpenRole: "closer",
    bats: "R", throws: "R",
    nationality: "🇨🇺 Cuba", age: 36, experience: 11,
    stats: { era: 0.00, whip: 0.62, ip: 9.2, k: 12, bb: 1, sv: 6, hold: null, games: 9 },
    statNote: "ACTIVATED AND IMMEDIATELY BACK IN THE 9TH — Iglesias was reinstated from the 15-day IL Tuesday morning (Carrasco DFA'd in the corresponding move), then closed out the 3-2 W in Seattle for his 6th save in his first appearance back. Spotless line now: 0.00 ERA, 0.62 WHIP, 5 H / 12 K / 1 BB across 9.2 IP. Robert Suarez slides back into a setup look (took the W Tuesday, 3-0).",
    form: 7.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33618.png",
    assignment: "mlb",
    contract: { years: 1, total: 16000000, guaranteed: 16000000, apy: 16000000, throughYear: 2026 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 3x 30-save season" },
    ],
  },
  {
    id: "suarez-robert",
    name: "Robert Suarez",
    number: 75,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "closer",
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 35, experience: 4,
    stats: { era: 0.66, whip: 0.81, ip: 13.2, k: 14, bb: 2, sv: 3, hold: 1, games: 14, w: 3, l: 0 },
    statNote: "FILLED IN AS CLOSER, NOW BACK TO SETUP — Suarez (W, 3-0) tossed a clean 8th in the 3-2 W in Seattle to bridge to Iglesias's return; he had been spotless during Iglesias's IL stint (3 SV / 0.66 ERA / 14:2 K:BB across 13.2 IP) and is now the team's premier setup arm with a closer-quality profile.",
    form: 8.7,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4148749.png",
    assignment: "mlb",
    contract: { years: 3, total: 45000000, guaranteed: 45000000, apy: 15000000, throughYear: 2028 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · 2x All-Star" },
      { years: "2022–2025", team: "San Diego Padres", type: "MLB" },
    ],
  },
  {
    id: "bummer",
    name: "Aaron Bummer",
    number: 48,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "lhp",
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 32, experience: 9,
    stats: { era: 4.35, whip: 1.36, ip: 10.1, k: 8, bb: 4, sv: 0, hold: null, games: 14, w: 0, l: 1 },
    statNote: "LH specialist — 14 G, 10.1 IP, 4.35 ERA. Walked McGonigle in relief Thu in DET's 5-2 sweep-avoiding W; the sac fly that followed went on the books as the go-ahead run. Still a high-leverage piece, but the recent results haven't matched the 98-game ATL track record.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/36131.png",
    assignment: "mlb",
    contract: { years: 2, total: 13000000, guaranteed: 13000000, apy: 6500000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
      { years: "2017–2023", team: "Chicago White Sox", type: "MLB" },
    ],
  },
  {
    id: "lee",
    name: "Dylan Lee",
    number: 52,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "lhp",
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 31, experience: 5,
    stats: { era: 1.23, whip: 0.55, ip: 14.2, k: 17, bb: 2, sv: 0, hold: null, games: 15, w: 1, l: 0 },
    statNote: "Quietly the best arm in the pen — 15 G, 1.23 ERA, 0.55 WHIP, 17 K against just 2 BB across 14.2 IP. Took the 8th in Saturday's loss vs PHI (Schwarber leadoff triple, Harper sac fly) but otherwise lights-out. Top lefty in the pen and still the highest-WAR arm among the Lee/Bummer/Kinley trio.",
    form: 6.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/41455.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2021–", team: "Atlanta Braves", type: "MLB · 2021 WS champ" },
    ],
  },
  {
    id: "kinley",
    name: "Tyler Kinley",
    number: 58,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 35, experience: 7,
    stats: { era: 1.29, whip: 1.14, ip: 14.0, k: 14, bb: 7, sv: 0, hold: null, games: 15, w: 3, l: 1 },
    statNote: "Hard-slider middle-relief arm — 15 G, 1.29 ERA, 14 K / 14 IP. Already 3-1 from middle relief; the offseason signing has been the biggest non-Suarez bullpen value-add of the year.",
    form: 6.8,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/34166.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2020–2025", team: "Colorado Rockies", type: "MLB" },
    ],
  },
  {
    id: "payamps",
    name: "Joel Payamps",
    number: 37,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 31, experience: 6,
    stats: { era: 8.22, whip: 1.70, ip: 7.2, k: 9, bb: 4, sv: 0, hold: null, games: 12, w: 0, l: 2 },
    statNote: "Designated for assignment May 1 alongside José Suárez when Stratton/Molina came up. Out of minor-league options. The Apr 30 lead-loss vs DET (Carpenter triple, Vierling double, walk to McGonigle) was his last Atlanta outing — 8.22 ERA across 12 G / 7.2 IP. The strike-thrower profile flashed (9 K) but the leverage trust never came back after April.",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd May 1, 2026 — off the 40-man.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40021.png",
    assignment: "mlb",
    contract: { years: 1, total: 3000000, guaranteed: 3000000, apy: 3000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2023–2025", team: "Milwaukee Brewers", type: "MLB" },
    ],
  },
  {
    id: "hamilton",
    name: "Ian Hamilton",
    number: 71,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 31, experience: 5,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Designated for assignment Apr 22 to clear a roster spot for Didier Fuentes' spot start. Off the 40-man.",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd Apr 22, 2026 — no longer on the Braves 40-man roster.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/41127.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2023–2025", team: "New York Yankees", type: "MLB" },
    ],
  },
  {
    id: "fuentes",
    name: "Didier Fuentes",
    number: 68,
    position: "SP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "R", throws: "R",
    nationality: "🇨🇴 Colombia", age: 20, experience: 1,
    stats: { era: 4.09, whip: 1.18, ip: 11.0, k: 14, bb: 3, sv: 0, hold: null, games: 4, starts: 1, w: 1, l: 0 },
    statNote: "FIRST CAREER WIN — 2 scoreless out of the pen in Friday's 8-6 comeback at Coors (5th-6th, 3 K, 1 H), inheriting and stranding a runner before Atlanta erupted for 8 unanswered. The 20-year-old (youngest SP in the majors) keeps cementing the long-relief / emergency-start role behind the bullpen. Apr 22 spot start vs WSH: 3 IP / 7 H / 4 ER (Braves still won 8-6).",
    form: 8.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5291189.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · MLB debut" },
    ],
  },
  {
    id: "dodd",
    name: "Dylan Dodd",
    number: 64,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 28, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "REHAB ASSIGNMENT BEGINS — Atlanta announced Tuesday May 5 that Dodd will start a rehab assignment with Triple-A Gwinnett (left thoracic spine inflammation since Apr 23). If it goes cleanly, the LH long man could rejoin the bullpen by Friday's series opener at Truist vs LAD, restoring a third lefty alongside Bummer and Lee.",
    form: 0,
    status: "il-15",
    injuryNote: "Left thoracic spine inflammation. 15-day IL since Apr 23. Triple-A Gwinnett rehab assignment began May 5; possible activation by the Friday LAD series opener.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4416462.png",
    assignment: "rehab",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "carrasco",
    name: "Carlos Carrasco",
    number: 59,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 39, experience: 16,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "RE-SIGNED AS GWINNETT DEPTH FRIDAY — Carrasco cleared waivers and re-signed with Atlanta on a minor-league deal, reporting to Triple-A Gwinnett for his fourth org stint of the year. The 39-year-old has effectively become a 41st-man arrangement — get summoned in MLB emergencies, run through waivers, re-sign. Logged 2.1 IP / 1 H / 0 ER / 2 K across his last two MLB games before the May 5 DFA.",
    form: 0,
    status: "departed",
    injuryNote: "Off the 40-man roster (DFA'd May 5, cleared waivers and re-signed to a minor-league deal May 8 — reporting to Triple-A Gwinnett as bullpen depth).",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/30976.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB (2nd stint)" },
      { years: "2009–2024", team: "Various (CLE, NYM, NYY)", type: "MLB · 2017 AL 18-win season" },
    ],
  },
  {
    id: "stratton",
    name: "Hunter Stratton",
    number: 65,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 29, experience: 3,
    stats: { era: 4.50, whip: 1.92, ip: 12.0, k: 18, bb: 5, sv: 0, hold: null, games: 11, w: 2, l: 2 },
    statNote: "OPTIONED BACK to Triple-A Gwinnett following Saturday night's win — the corresponding move that cleared a roster spot for Spencer Strider's Sunday activation. Three-day big-league cameo this trip with no game appearance. Power righty acquired from Pittsburgh in July 2025 (for Titus Dumitru); the Achilles/knee rehab is finished and he sits as the next-up bullpen arm at Gwinnett.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4987652.png",
    assignment: "aaa",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB" },
      { years: "2023–2025", team: "Pittsburgh Pirates", type: "MLB · debut 2023" },
    ],
  },
  {
    id: "molina-anthony",
    name: "Anthony Molina",
    number: 67,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 24, experience: 2,
    stats: { era: 4.50, whip: 1.36, ip: 14.0, k: 10, bb: 3, sv: 0, hold: null, games: 5, starts: 2, w: 1, l: 2 },
    statNote: "CONTRACT SELECTED MAY 1 from Triple-A Gwinnett alongside Stratton's recall. Four-pitch strike-thrower (4-seam, slider, change, two-seam) claimed off waivers from Colorado in December 2025. Made his MLB debut as a Rule 5 pick on 2024 Opening Day with COL (35 G, 6.79 ERA). Adds long-relief / spot-start depth behind the bullpen with Suárez and Payamps gone.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5016983.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2024–2025", team: "Colorado Rockies", type: "MLB · Rule 5 pick from TB 2023" },
    ],
  },

  // ── TRIPLE-A DEPTH (recall candidates on 40-man, optioned to Gwinnett) ─────
  {
    id: "munoz-rolddy",
    name: "Rolddy Muñoz",
    number: 78,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 26, experience: 2,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Power righty — 97-98 mph FB, slider-heavy. 7.2 scoreless IP / 7 K through first 5 at Gwinnett. Optioned back down when Dodd was recalled Apr 21; next man up in a bullpen emergency.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5131982.png",
    assignment: "aaa",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB · MLB debut 2025" },
    ],
  },

  // ── INJURED LIST ────────────────────────────────────────────────────────────
  {
    id: "strider",
    name: "Spencer Strider",
    number: 99,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 2,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 27, experience: 5,
    stats: { era: 8.10, whip: 2.70, ip: 3.1, k: 6, bb: 5, w: 0, l: 0, games: 1, starts: 1 },
    statNote: "TONIGHT AT DODGER STADIUM — Strider gets the ball Saturday vs LAD's Roki Sasaki (1-3, 5.97) at 9:10 PM ET, his second start of 2026 after the rocky Coors debut May 3 (3.1 IP / 4 H / 3 ER / 5 BB / 6 K, ND in the 11-6 sweep-clinching W). The five walks tied a career high; stuff was there (96+ FB) but command lagged after the long oblique-strain layoff. Atlanta swapped him into the Saturday slot ahead of Ritchie to align his work week — Holmes/Ritchie pushed back to the WSH homestand.",
    form: 6.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4307825.png",
    assignment: "mlb",
    contract: { years: 6, total: 75000000, guaranteed: 75000000, apy: 12500000, throughYear: 2028 },
    career: [
      { years: "2021–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2023 NL Ks leader" },
    ],
  },
  {
    id: "murphy",
    name: "Sean Murphy",
    number: 12,
    position: "C",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 31, experience: 7,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "BENCH FRIDAY VS SHEEHAN — Murphy sat for the LAD opener (LHP Sheehan) after going 1-for-6 with three K's vs the Mariners. Baldwin started behind the plate with Dominic Smith taking the DH at-bats. Walt Weiss is phasing Murphy in around the post-hip-surgery recovery rather than rushing a 50/50 split with Baldwin from Day 1. He hit .333 (8-for-24) at Gwinnett before activation. The catching room remains Baldwin-first, Murphy-rebuilding through May.",
    form: 7.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33557.png",
    assignment: "mlb",
    contract: { years: 6, total: 73000000, guaranteed: 73000000, apy: 12166666, throughYear: 2028 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB · 2023 NL All-Star · Gold Glove" },
      { years: "2019–2022", team: "Oakland Athletics", type: "MLB" },
    ],
  },
  {
    id: "kim",
    name: "Ha-Seong Kim",
    number: 7,
    position: "SS",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇰🇷 South Korea", age: 30, experience: 5,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Officially began his major-league rehab assignment Tuesday (Apr 28) with the Double-A Columbus Clingstones — the first MLB rehab assignment in Clingstones franchise history. Walt Weiss said pre-game that Kim will need \"a couple of weeks\" of at-bats before the Braves consider promoting him; mid-May target for the Atlanta debut still holds.",
    form: 0,
    status: "il-60",
    injuryNote: "Torn tendon right middle finger (Jan 2026 surgery — slipped on ice in South Korea). Rehab assignment underway at Double-A Columbus (six-game homestand vs Montgomery opened Apr 28). \"A couple of weeks\" timetable per Weiss; mid-May Atlanta target.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4089862.png",
    assignment: "rehab",
    contract: { years: 2, total: 24000000, guaranteed: 24000000, apy: 12000000, throughYear: 2027 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2021–2025", team: "San Diego Padres", type: "MLB · Gold Glove" },
    ],
  },
  {
    id: "smith-shawver",
    name: "AJ Smith-Shawver",
    number: 60,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 23, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, w: null, l: null, games: null, starts: null },
    statNote: "Tommy John June 2025 — return window 2026 or 2027 season.",
    form: 0,
    status: "il-60",
    injuryNote: "Tommy John surgery (Jun 2025). Return: late 2026 or 2027.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4917640.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "waldrep",
    name: "Hurston Waldrep",
    number: 66,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 24, experience: 2,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, w: null, l: null, games: null, starts: null },
    statNote: "Set to throw his first bullpen session this week — Walt Weiss confirmed pre-game Apr 28. Targeted return remains June for game action.",
    form: 0,
    status: "il-60",
    injuryNote: "Right elbow inflammation; post-arthroscopic surgery Feb 23. First post-surgery bullpen session scheduled for this week (per Weiss, Apr 28). Targeted return: June.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4740117.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB · 2023 R1 pick" },
    ],
  },
  {
    id: "schwellenbach",
    name: "Spencer Schwellenbach",
    number: 56,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 26, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, w: null, l: null, games: null, starts: null },
    statNote: "Recovering from offseason arthroscopic elbow surgery.",
    form: 0,
    status: "il-60",
    injuryNote: "Arthroscopic elbow surgery. Targeted return: late June / July.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4424862.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "jimenez",
    name: "Joe Jiménez",
    number: 77,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: null,
    bats: "R", throws: "R",
    nationality: "🇵🇷 Puerto Rico", age: 31, experience: 9,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Knee surgery — no timetable.",
    form: 0,
    status: "il-60",
    injuryNote: "Left knee surgery. No timetable for return.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33760.png",
    assignment: "mlb",
    contract: { years: 3, total: 26000000, guaranteed: 26000000, apy: 8666666, throughYear: 2026 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB · 2018 AL All-Star" },
    ],
  },
  {
    id: "young",
    name: "Danny Young",
    number: 69,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: null,
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 30, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Transferred to 60-day IL Apr 11. Could return after the All-Star break.",
    form: 0,
    status: "il-60",
    injuryNote: "Tommy John (May 2025). Transferred to 60-day IL Apr 11.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40903.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
];

// ─── RSS FEEDS (news pipeline) ─────────────────────────────────────────────────
export const RSS_FEEDS = [
  {
    name: "MLB.com Braves",
    url: "https://www.mlb.com/braves/feeds/news/rss.xml",
    category: "official",
  },
  {
    name: "Battery Power",
    url: "https://www.batterypower.com/rss/index.xml",
    category: "fan",
  },
  {
    name: "AJC Braves",
    url: "https://www.ajc.com/arc/outboundfeeds/rss/section/sports/braves/",
    category: "major",
  },
  {
    name: "MLB Trade Rumors – Braves",
    url: "https://www.mlbtraderumors.com/atlanta-braves/feed",
    category: "major",
  },
  {
    name: "Talking Chop",
    url: "https://www.talkingchop.com/rss/index.xml",
    category: "fan",
  },
];

// ─── TEAM LOGOS (NL East + recent opponents) ────────────────────────────────────
export const TEAM_LOGOS = {
  ATL: "https://a.espncdn.com/i/teamlogos/mlb/500/atl.png",
  PHI: "https://a.espncdn.com/i/teamlogos/mlb/500/phi.png",
  NYM: "https://a.espncdn.com/i/teamlogos/mlb/500/nym.png",
  WSH: "https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png",
  MIA: "https://a.espncdn.com/i/teamlogos/mlb/500/mia.png",
  KC:  "https://a.espncdn.com/i/teamlogos/mlb/500/kc.png",
  LAD: "https://a.espncdn.com/i/teamlogos/mlb/500/lad.png",
  SD:  "https://a.espncdn.com/i/teamlogos/mlb/500/sd.png",
  NYY: "https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png",
  HOU: "https://a.espncdn.com/i/teamlogos/mlb/500/hou.png",
};

// ─── UPCOMING SCHEDULE ─────────────────────────────────────────────────────────
// The next ~5 scheduled games used by the rotation map / probable-pitchers strip.
// Skill maintains this each daily run: drop today's game once it moves to RESULTS,
// add a new tail entry. atlSP.id should match a PLAYERS entry so the avatar can
// render; use null for true TBAs. daysRest is calendar days since last MLB start.
export const UPCOMING_SCHEDULE = [
  {
    date: "2026-05-09",
    weekday: "Sat",
    time: "9:10 PM ET",
    opp: "LAD",
    home: false,
    venue: "Dodger Stadium",
    atlSP: { id: "strider", name: "Spencer Strider", record: "0-0", era: 8.10, daysRest: 6, hand: "R" },
    oppSP: { name: "Roki Sasaki", record: "1-3", era: 5.97, hand: "R" },
    note: "TONIGHT — Strider's 2nd 2026 start after the rocky Coors debut · Sasaki (1-3, 5.97) coming off command issues · ATL swapped Strider into Sat slot ahead of Ritchie",
  },
  {
    date: "2026-05-10",
    weekday: "Sun",
    time: "4:10 PM ET",
    opp: "LAD",
    home: false,
    venue: "Dodger Stadium",
    atlSP: { id: "elder", name: "Bryce Elder", record: "3-1", era: 2.02, daysRest: 6, hand: "R" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Elder on regular rest after the 9-K Seattle masterpiece · LAD series finale · Mother's Day matinee on the West Coast",
  },
  {
    date: "2026-05-12",
    weekday: "Tue",
    time: "7:20 PM ET",
    opp: "WSH",
    home: true,
    venue: "Truist Park",
    atlSP: { id: "holmes", name: "Grant Holmes", record: "2-1", era: 4.50, daysRest: 12, hand: "R" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Truist HOMESTAND OPENER vs WSH — Holmes finally gets the ball after the Strider/Pérez schedule churn · 12 days since Holmes's last MLB outing (Coors May 1) · possible Acuña activation day",
  },
  {
    date: "2026-05-13",
    weekday: "Wed",
    time: "7:20 PM ET",
    opp: "WSH",
    home: true,
    venue: "Truist Park",
    atlSP: { id: "ritchie", name: "JR Ritchie", record: "1-0", era: 3.63, daysRest: 12, hand: "R" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Ritchie's first start since Apr 29 vs DET — pushed back when Strider was slotted into the LAD Saturday game · sea-level Truist after the rocky Seattle homecoming",
  },
];

// ─── NEXT GAME ──────────────────────────────────────────────────────────────────
export const NEXT_GAME = {
  date: "2026-05-09",
  time: "9:10 PM ET",
  opp: "LAD",
  home: false,
  venue: "Dodger Stadium · Los Angeles, CA",
  tv: "FanDuel Sports Network Southeast",
  probables: {
    atl: { pitcher: "Spencer Strider", record: "0-0", era: 8.10 },
    opp: { pitcher: "Roki Sasaki", record: "1-3", era: 5.97 },
  },
  note: "TONIGHT — STRIDER vs SASAKI AT CHAVEZ RAVINE — Atlanta (26-13, .684, still MLB-best) looks to even the series at Dodger Stadium after Friday's 3-1 L (Sale tough-luck, Freeman 100th-as-a-Dodger HR). Spencer Strider (0-0, 8.10) makes his second start of 2026 — the Braves swapped him into the Saturday slot ahead of JR Ritchie to align his throw day, with Holmes/Ritchie pushed back to the WSH homestand. Roki Sasaki (1-3, 5.97 ERA, 1.67 WHIP, 26 K / 15 BB across 28.2 IP) opposes — the Dodgers right-hander has scuffled with command and reportedly was open to a minor-league assignment. Acuña Jr. has 'a very good chance' to be back Wednesday at Truist (first IL-eligible day) per Weiss; Harris II returned to CF Friday and went 4-for-4; Murphy back behind the plate Saturday vs the RH Sasaki. First pitch 6:10 PT / 9:10 PM ET — Game 2 of 3.",
};

// ─── RECENT RESULTS ─────────────────────────────────────────────────────────────
export const RESULTS = [
  { date: "2026-05-08", opp: "LAD", home: false, atlScore: 1, oppScore: 3, result: "L", note: "FREEMAN HOMERS, OHTANI DRIVES IN GO-AHEAD RUN — The Dodgers won the series opener 3-1, dropping Atlanta to 26-13. Chris Sale (LP, 6-2) was excellent in defeat: 7 IP / 5 H / 3 R / 2 ER / 7 K / 0 BB. Austin Riley's 2nd-inning RBI single off Emmet Sheehan gave Atlanta a brief 1-0 lead before Sheehan struck out the next two. Kyle Tucker's bloop RBI double in the bottom of the 2nd tied it. With two outs in the 5th, Miguel Rojas reached on an error and Shohei Ohtani lined an RBI single up the middle to put LAD ahead 2-1. Freddie Freeman led off the 6th with a 413-ft HR to CF (#4) — his 100th career HR as a Dodger, joining 36 others to do so in franchise history. Sheehan: 4.2 IP / 6 H / 1 ER / 1 BB / 7 K. The LAD bullpen (Vesia W 1-0, Hurt, Klein, Stewart, Tanner Scott SV #3) shut ATL down for the final 4.1 innings. Michael Harris II went 4-for-4 batting cleanup in his return to CF (just the 10th cleanup start of his career). Atlanta dropped its 8th straight game at Dodger Stadium. Pregame: Carlos Carrasco re-signed to a minor-league deal and reported to Triple-A Gwinnett." },
  { date: "2026-05-06", opp: "SEA", home: false, atlScore: 1, oppScore: 3, result: "L", note: "FIRST SERIES LOSS OF 2026 — Bryan Woo (W, 2-2) shut Atlanta down in the rubber match: 6 IP / 1 H / 2 BB / 9 K (tied his season-high) on a season-high 98 pitches (66 strikes). Mauricio Dubón's two-out single in the 4th was the Braves' ONLY hit off Woo; ATL finished with 4 H, 2 BB, and 12 K total. Pereda led off the 3rd with a single, Leo Rivas doubled, and J.P. Crawford walked to load the bases — Cal Raleigh's 6-4-3 DP scored the first run, and Cole Young (3-for-4, 2 doubles) added an RBI 2B in the same inning. Julio Rodríguez crushed a solo HR (#5) in the 6th off Pérez. José Ferrer pitched a 1-2-3 9th for his 2nd save. Martín Pérez (LP, 2-2): 5.2 IP / 5 H / 2 ER / 3 BB / 5 K — quality start wasted. Atlanta drops to 26-12; the eight-series win streak (and 10-0-1 series mark to open the year) is over. Pregame roster move: SS/IF JIM JARVIS selected from Triple-A Gwinnett for his MLB debut (started SS, batted 9th); José Azocar DFA'd in the corresponding move." },
  { date: "2026-05-05", opp: "SEA", home: false, atlScore: 3, oppScore: 2, result: "W", note: "OLSON WALKS BACK SEATTLE — Matt Olson led off the 9th with a 110-mph, 412-ft tiebreaking HR (NL-leading #13) into the LCF seats off Mariners closer Andrés Muñoz on a hung 2-1 slider, lifting Atlanta past Seattle 3-2 and to 26-11. Bryce Elder (ND): 6 IP / 2 H / 2 ER / 3 BB / 9 K (season-high) — only blemish a Cal Raleigh solo HR. George Kirby (ND for SEA): 7 IP / 5 H / 2 ER / 1 BB / 5 K. Robert Suarez (W, 3-0) tossed a clean 8th. Pre-game roster moves: Raisel Iglesias activated from the 15-day IL (Carrasco DFA'd in the corresponding move); Iglesias closed the 9th for his 6th save in his first appearance back. Dylan Dodd began a Triple-A Gwinnett rehab assignment; he could rejoin the bullpen by Friday's LAD opener. Walt Weiss also confirmed Michael Harris II will be DH-only for the next ~week to nurse the left quad without an IL trip." },
  { date: "2026-05-04", opp: "SEA", home: false, atlScore: 4, oppScore: 5, result: "L", note: "MARINERS WALK BACK A 4-0 LEAD — Atlanta jumped Logan Gilbert with FOUR solo HRs (Drake Baldwin leadoff to CF, Albies and Olson back-to-back to start the 6th, Austin Riley right after) — but Olson's blast was historic on its own: a 428-ft shot to LCF that made him the 166th player to 300 career home runs. Then the bottom of the 6th unspooled it: JR Ritchie (ND) walked the first two and Luke Raley turned on a 3-run HR; Crawford added a go-ahead 2-run HR off the pen for the 5-4 lead Seattle never gave back. Final pitching line for Ritchie: 5 IP / 4 H / 3 ER / 6 BB / 2 K (47-of-93 strikes). Atlanta drops to 25-11, ending a 3-game W streak. Pregame: Sean Murphy reinstated from the 60-day IL after his Gwinnett rehab (.333 / 4 RBI); Jonah Heim DFA'd in the corresponding move. (Heim later traded to OAK for cash Tuesday.)" },
  { date: "2026-05-03", opp: "COL", home: false, atlScore: 11, oppScore: 6, result: "W", note: "SWEEP COMPLETE, STRIDER SURVIVES — Atlanta's offense bailed out a rocky 2026 debut from Spencer Strider in an 11-6 series-clinching win at Coors. Strider (ND): 3.1 IP / 4 H / 3 ER / 5 BB / 6 K, gave up a 423-ft leadoff HR to TJ Rumfield in the 3rd; the five walks tied a career high. JONAH HEIM was the headline bat: career-high-tying 5 RBI on a 2nd-inning 420-ft HR off Quintana (back-to-back with Jorge Mateo's #2), a bases-loaded sac fly in the 5th, and a 2-out 2-run double in the 9th. Mateo's 2-run HR. Atlanta now 25-10 — the franchise's best 35-game start in 134 years, best in the modern era. Pregame: Acuña placed on the 10-day IL with a Grade 1 hamstring strain (MRI), Azocar selected from Triple-A Gwinnett; Stratton optioned to Gwinnett (Sat night) to clear the spot for Strider's activation." },
  { date: "2026-05-02", opp: "COL", home: false, atlScore: 9, oppScore: 1, result: "W", note: "SALE DOMINATES AT ALTITUDE, BALDWIN ALMOST CYCLES — Atlanta's MLB-best record climbs to 24-10 in a 9-1 rout at Coors. Chris Sale (W, 6-1) was masterful: 7 IP / 3 H / 1 ER / 11 K — MLB-leading 6th W and a Coors line that's almost unheard of. Drake Baldwin (3-for-4, 4 RBI) opened the scoring with a 2-run HR (#8) off COL LHP Brennan Bernardino (LP, 2-1) in the 1st, then doubled and singled — a triple short of the cycle. Olson #11 (now MLB co-leader) and Riley #4 added insurance. Lone scare: Ronald Acuña Jr. exited in the 2nd inning with left hamstring tightness after pulling up halfway down the line on a grounder; he walked off gingerly and will undergo an MRI. Atlanta now 14 of last 17, 7.5+ GM up on MIA in the NL East and best record in MLB by 1.5 over LAD." },
  { date: "2026-05-01", opp: "COL", home: false, atlScore: 8, oppScore: 6, result: "W", note: "INSTANT CLASSIC AT COORS — Atlanta erased a 6-0 deficit with EIGHT UNANSWERED runs, capped by Michael Harris II's pinch-hit 2-run HR off Tyler Kinley in the 9th. Tied for the franchise's largest comeback ever at Coors Field. Holmes got bullied by altitude (4 IP / 4 ER / 6 H, ND); Quintana matched zeros for COL through 4. The Braves scratched a run in the 7th, then exploded for 4 in the 8th — Mauricio Dubón's BASES-LOADED TRIPLE the dagger that tied it 6-6, with Olson's #10 HR fueling the cushion. Didier Fuentes (W, 1-0) went 2 scoreless out of the pen (5th–6th, 3 K). Pierce Johnson worked a clean 9th for his first save. Atlanta moves to 23-10 and 7.5 GM up on MIA. Pregame: Suárez and Payamps DFA'd; Stratton and Molina recalled/selected from Triple-A Gwinnett." },
  { date: "2026-04-30", opp: "DET", home: true,  atlScore: 2, oppScore: 5, result: "L", note: "Tigers avoid the sweep with a 4-run 8th. Bryce Elder (ND) was excellent: 6 IP / 6 H / 1 ER / 3 BB / 5 K, exiting with a 2-1 lead. Joel Payamps gave up Carpenter's leadoff triple to start the 8th and Vierling's tying double chased him; Aaron Bummer relieved, walked McGonigle, then Gleyber Torres's go-ahead sac fly made it 3-2. José Suárez (LP) walked Pérez and Hao-Yu Lee in the 9th, Yastrzemski misplayed Vierling's third hit for an error, and Dingler's double iced it at 5-2. Atlanta still takes the series 2-1; the 10-game ATL streak vs DET ends. Tigers finish April 14-13 and stay atop the AL Central at 16-16 on the trip." },
  { date: "2026-04-29", opp: "DET", home: true,  atlScore: 4, oppScore: 3, result: "W", note: "WALK-OFF — Matt Olson clubbed a 2-run, 397-ft HR (#9) into the Atlanta bullpen off ex-Brave Kenley Jansen on the 5th pitch of the AB, after Albies opened the 9th with a walk. Spoiled a dominant Tarik Skubal start (7 IP / 5 H / 2 ER / 0 BB / 7 K, 91 pitches) — Albies 2-run HR (#7) in the 1st was Atlanta's only damage off the AL Cy Young. JR Ritchie pitched into the 6th in his second MLB start (ND); a pickoff-throw error on McGonigle in the 2nd let DET tie it. Reynaldo López (W, 2-1) was the difference: 2 scoreless / 0 H / 2 K out of the pen in the 8th–9th. Tigers closer Jansen has now allowed walk-off HRs in back-to-back outings." },
  { date: "2026-04-28", opp: "DET", home: true,  atlScore: 5, oppScore: 2, result: "W", note: "Martín Pérez (W, 2-1) tossed 5 scoreless on 2 H / 4 BB / 5 K in the series opener vs the AL Central champs — first W over Detroit since Aug 25, 2019. Yastrzemski/Acuña hit back-to-back doubles in the 3rd, Acuña scored on Olson's sac fly for a 2-0 lead, and Albies smashed a 2-run HR (#6, 377 ft, 98.5 mph EV) off Tyler Holton in the 8th to put it away. DET RHP Casey Mize (LP, 2-2) left after 2.1 IP with right groin tightness. Atlanta improves to 21-9, tied with LAD for best in MLB." },
];

// ─── NL EAST STANDINGS ──────────────────────────────────────────────────────────
export const NL_EAST_STANDINGS = [
  { team: "ATL", name: "Atlanta Braves",         w: 26, l: 13, pct: .667, gb: 0,    streak: "L2" },
  { team: "WSH", name: "Washington Nationals",   w: 18, l: 21, pct: .462, gb: 8,    streak: "W2" },
  { team: "PHI", name: "Philadelphia Phillies",  w: 17, l: 22, pct: .436, gb: 9,    streak: "L2" },
  { team: "MIA", name: "Miami Marlins",          w: 17, l: 22, pct: .436, gb: 9,    streak: "L1" },
  { team: "NYM", name: "New York Mets",          w: 15, l: 23, pct: .395, gb: 10.5, streak: "W1" },
];

// ─── NEWS DIGEST — the recency-biased summary the skill refreshes daily ──────────
export const NEWS_DIGEST = {
  generatedAt: "2026-05-09T09:00:00-04:00",
  summary:
    "STRIDER vs SASAKI TONIGHT AT CHAVEZ RAVINE AFTER FRIDAY'S 3-1 OPENING-NIGHT L — The Dodgers took the LAD-ATL series opener 3-1 Friday night despite a strong Chris Sale outing (LP, 6-2: 7 IP / 5 H / 3 R / 2 ER / 7 K / 0 BB). Freddie Freeman led off the 6th with his 100th career HR as a Dodger (#4, 413 ft to CF — joining 36 others to do so), Shohei Ohtani drove in the go-ahead run on a 2-out, 5th-inning RBI single after a Rojas error, and Kyle Tucker's 2nd-inning bloop RBI double tied things up after Austin Riley's RBI single off Sheehan. The Dodgers bullpen (Vesia W, Hurt, Klein, Stewart, Tanner Scott SV #3) shut Atlanta down for the final 4.1. Michael Harris II went 4-for-4 batting cleanup in his return to CF — quad-strain DH-only window over. Atlanta's 8th straight L at Dodger Stadium dropped them to 26-13 (.667). For Game 2, Atlanta swapped Spencer Strider (0-0, 8.10) into the Saturday slot ahead of JR Ritchie to align his throw day; he draws Roki Sasaki (1-3, 5.97 ERA, 1.67 WHIP, 26 K / 15 BB) — the Dodgers RHP who reportedly has been open to a minor-league assignment. WALT WEISS SAID FRIDAY ACUÑA HAS A 'VERY GOOD CHANCE' TO BE BACK WEDNESDAY — May 13, the first IL-eligible day, vs WSH at Truist. He was on the field doing agility work at Dodger Stadium with 'a few boxes left to check.' NL EAST LEAD HOLDS AT 8.0 GB OVER WSH (18-21, W2 over MIA) — Phillies fell 9-7 in 11 to COL (Crawford rookie HR pushed it to extras), Marlins lost 3-2 at home to WSH, Mets edged ARI 4-3 at Chase. Standings now: ATL 26-13, WSH 18-21 (-8.0), PHI 17-22 (-9.0), MIA 17-22 (-9.0), NYM 15-23 (-10.5). Olson (NL-leading 13 HR, .295/.366/.631, .997 OPS, 33 RBI) hitless Friday but still atop the NL leaderboard; Harris II's 4-for-4 makes him the new team batting leader at .345.",
  keyTopics: [
    { category: "result",      title: "L 1-3 at LAD Fri — Freeman 100th-as-Dodger HR, Ohtani RBI single decide it",         detail: "Sale (LP, 6-2): 7 IP / 5 H / 3 R / 2 ER / 7 K / 0 BB — quality start wasted. Riley's 2nd-inning RBI single gave ATL a brief 1-0 lead before Sheehan struck out the next two. Tucker's bloop RBI double tied it. With 2 outs in the 5th, Rojas reached on an error and Ohtani lined an RBI single up the middle. Freeman led off the 6th with a 413-ft solo HR (#4) — his 100th as a Dodger. Sheehan: 4.2 IP / 6 H / 1 ER / 1 BB / 7 K (W: Vesia 1-0, SV: Tanner Scott #3). Atlanta's 8th straight L at Dodger Stadium." },
    { category: "rotation",    title: "TONIGHT — Strider (0-0, 8.10) vs Sasaki (1-3, 5.97) at Dodger Stadium",                detail: "Spencer Strider gets the ball Saturday at 9:10 PM ET — his 2nd start of 2026 after the rocky Coors debut May 3. ATL swapped him into the Saturday slot ahead of JR Ritchie to align his throw week, with Holmes/Ritchie pushed to the WSH homestand (Tue/Wed). Sasaki (1-3, 5.97 ERA, 1.67 WHIP, 26 K / 15 BB across 28.2 IP) opposes — the Dodgers RHP has scuffled with command and reportedly has been open to a minor-league assignment. First pitch 6:10 PT / 9:10 PM ET on FDSSE." },
    { category: "injury",      title: "Acuña 'very good chance' to return Wednesday May 13 — first IL-eligible day",         detail: "Walt Weiss said pre-game Friday that Acuña has a 'very good chance' to be back in the lineup Wednesday May 13 vs WSH — the earliest day he's eligible to come off the 10-day IL (Grade 1 left hamstring). Acuña was seen on the field doing agility work at Dodger Stadium and has 'a few boxes left to check.' MRI results were positive and revealed no significant damage. Eli White / Bairon Velandia / Jorge Mateo continue to split RF reps." },
    { category: "lineup",      title: "Harris II back in CF, 4-for-4 batting cleanup — quad window over",                    detail: "Michael Harris II returned to center field Friday and went 4-for-4 batting cleanup for just the 10th time in his career — clear sign the left quad has settled enough to get him back in the field after a week of DH-only usage. Slash now .345/.376/.578 (.954 OPS), 7 HR / 22 RBI in 32 G — back atop the team in average and OPS as Olson cooled. Removing the 'day-to-day' label going forward unless the quad flares again." },
    { category: "standings",   title: "NL East lead holds at 8.0 GB — WSH up to 2nd at 18-21",                                detail: "Atlanta's 26-13 record stays comfortably ahead. WSH won 3-2 at MIA (W2) to climb to 18-21 — now 8.0 back. PHI fell 9-7 in 11 at home to COL (Crawford rookie HR pushed it to extras after a 6-0 PHI hole; Goodman 4 H / HR for COL) — drop to 17-22 (L2). MIA L 3-2 to WSH at home (L1). NYM beat ARI 4-3 at Chase (W1). Standings: ATL 26-13, WSH 18-21 (-8), PHI 17-22 (-9), MIA 17-22 (-9), NYM 15-23 (-10.5)." },
    { category: "transaction", title: "Carrasco re-signed to MiLB deal — back to Gwinnett for stint #4",                     detail: "Carlos Carrasco cleared waivers after Tuesday's DFA and re-signed with Atlanta on a minor-league deal Friday, reporting to Triple-A Gwinnett for his fourth org stint of the season. The 39-year-old veteran has effectively become Atlanta's 41st man — summoned in MLB emergencies, then waived and re-signed. Logged 2.1 IP / 1 H / 0 ER / 2 K across his last two MLB games before the May 5 cut. Iglesias's IL activation that week needed the 40-man spot." },
    { category: "narrative",   title: "Three-game showdown at LAD — Atlanta's stiffest test of the year",                    detail: "ATL (26-13, MLB-best) at LAD (25-15, Ohtani-Freeman-Betts-Yamamoto) at Chavez Ravine for the weekend. The Dodgers have been Atlanta's October stone wall (10-3 in postseason play vs ATL all time) and have now beaten the Braves eight straight at Dodger Stadium across regular-season visits. Game 2 (Strider/Sasaki) Saturday, Game 3 (Elder/TBA) Sunday afternoon — Mother's Day matinee on the West Coast." },
    { category: "milestone",   title: "Olson hitless Friday but still NL HR leader (13)",                                    detail: "Olson went 0-fer in his first action vs the LAD bullpen mix Friday, dropping his slash to .295/.366/.631 (.997 OPS) but holding onto the NL HR lead at 13 through 38 G. The 33 RBI is also NL top-tier; Saturday's spot vs Sasaki (1.67 WHIP, command issues) sets up a clear bounce-back opportunity. The 9th-inning go-ahead bomb in Seattle Tuesday and Monday's 300th-career HR remain the May centerpiece." },
    { category: "milestone",   title: "Sale's NL-leading 56 K — 7 IP / 7 K / 0 BB at Dodger Stadium kept the streak going",  detail: "Sale's strikeout lead grew despite the L Friday: 7 K / 0 BB at Chavez Ravine pushes him to 56 K across 49 IP, NL-leading and top-15 in MLB. ERA up just slightly to 2.20, WHIP holds at 0.82. He's allowed two earned runs or fewer in seven of his eight starts. Tough-luck 6-2 record because Atlanta has scored 2 or fewer runs in three of his eight starts." },
    { category: "milestone",   title: "Harris II takes over team batting lead — .345/.376/.578",                              detail: "After the 4-for-4 Friday, Michael Harris II's slash line jumps to .345/.376/.578 (.954 OPS), 7 HR / 22 RBI in 32 G — passing both Albies (.313) and Baldwin (.315) for the team batting lead. Albies still leads in hits (45) and is steady at .313/.358/.533 (.891 OPS), 8 HR / 23 RBI in 37 G. With Acuña likely back Wednesday, the lineup is staring at full strength again before the WSH homestand winds down." },
    { category: "transaction", title: "Murphy back behind the plate Saturday vs RH Sasaki",                                  detail: "Sean Murphy sat Friday vs Sheehan (LHP) — Drake Baldwin caught and Dominic Smith took the DH at-bats. With Sasaki (RHP) on the mound Saturday, Murphy is expected back behind the plate as Walt Weiss continues phasing him in around the post-hip-surgery recovery rather than rushing a 50/50 split with Baldwin. He hit .333 (8-for-24) at Gwinnett before activation; the catching room remains Baldwin-first through May." },
    { category: "transaction", title: "Dodd's Gwinnett rehab clean — activation expected this weekend / early next week",     detail: "LHP Dylan Dodd (left thoracic spine inflammation, 15-day IL since Apr 23) made a clean rehab outing for Triple-A Gwinnett Tuesday but the Braves did NOT reinstate him before the LAD opener. Likely target is the rest of the LAD weekend or the WSH homestand opener Tuesday. Restores a third lefty in the bullpen alongside Bummer and Lee. Corresponding move TBD — Stratton or Molina the likely option-down candidates." },
    { category: "injury",      title: "Kim's Triple-A rehab continuing; mid-May Atlanta debut still in play",                detail: "Ha-Seong Kim's right middle finger torn tendon (Jan 2026 surgery) rehab is now at Triple-A Gwinnett after the Apr 28 transfer up from Double-A Columbus. Weiss still targeting mid-May for the activation. Dubón continues to bridge at SS; Mateo and Jarvis split the secondary middle-IF reps. With Acuña possibly back May 13, the next two roster reshuffles are queued up." },
  ],
  sources: [
    "MLB.com", "ESPN", "AJC", "Battery Power", "MLB Trade Rumors", "CBS Sports", "Yahoo Sports", "Baseball-Reference", "FanGraphs", "AP", "Atlanta News First", "Yardbarker", "Fox Sports", "RotoWire", "FantasyPros", "True Blue LA", "Dodger Blue", "Dodgers Beat", "Washington Post", "WRAL", "Sporting Tribune", "Athlon Sports", "ClutchPoints", "SI", "Heavy.com",
  ],
};
