// ─── Atlanta Braves Player Data (2026 Season · Updated May 7, 2026) ──────────
// Single source of truth for roster, games, standings, digest, and RSS feeds.
// Season context: 26-12 (.684) — still atop the NL East by 8.5 over PHI (17-20),
// MLB-best, but the eight-series win streak is finally broken. ATL DROPS THE
// SEATTLE RUBBER MATCH 3-1 in a flat offensive performance — Bryan Woo was
// dominant (6 IP / 1 H / 2 BB / 9 K, 98 pitches) and Atlanta managed just
// FOUR HITS / TWELVE STRIKEOUTS against the Mariners' staff. Mauricio Dubón's
// two-out single in the 4th was the only knock off Woo. Martín Pérez (LP, 2-2)
// took the L in a quality start: 5.2 IP / 5 H / 2 ER / 5 K — Cole Young (3-for-4,
// 2B, 2B) and Julio Rodríguez (solo HR #5 off Pérez in the 6th) did the damage.
// José Ferrer save (#2). Roster move: BRAVES SELECT 25-YO INFIELDER JIM JARVIS
// from Triple-A Gwinnett (.305/.418/.445, 4 HR, 15 SB across 33 G) for his MLB
// debut — he started at SS to give Mateo a day. JOSÉ AZOCAR DFA'd in the
// corresponding move (just three days after his Apr 3 selection). Today is a
// TRAVEL DAY ahead of a marquee three-game series at DODGER STADIUM (away)
// starting Friday: Sale (6-1, 2.14) vs Emmet Sheehan in the opener. Acuña
// (Grade 1 left hamstring) still on the 10-day IL; Harris stays DH-only for
// ~7 days; Murphy easing back; Iglesias secure as closer (6 SV); Dodd's
// Triple-A rehab outing went well — could rejoin the bullpen by Friday.
//
// Statuses: "active" | "day-to-day" | "questionable" | "il-10" | "il-15" | "il-60" | "suspended" | "departed"
// Assignments: "mlb" | "aaa" | "aa" | "rehab"  (org-level location, orthogonal to injury status)
//   mlb   = on the 26/40-man active roster with the big club
//   aaa   = optioned or stashed at Triple-A Gwinnett (recall candidate)
//   aa    = lower-level depth (rare; used for high-profile prospects only)
//   rehab = on IL + currently on a minor-league rehab assignment
// injuryNote: short description shown on card when not active

export const PLAYERS = [
  // ── STARTING LINEUP ─────────────────────────────────────────────────────────
  {
    id: "acuna",
    name: "Ronald Acuña Jr.",
    number: 13,
    position: "RF",
    positionGroup: "batter",
    lineupSpot: 1,
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 28, experience: 8,
    stats: { avg: .238, obp: .349, slg: .368, ops: .717, hr: 2, rbi: 9, sb: 6, bb: 19, so: 32, games: 34 },
    statNote: "ON THE 10-DAY IL (May 3) — MRI confirmed a Grade 1 strain of the left hamstring. Manager Walt Weiss: 'Not too serious, but serious enough that we had to put him on the list.' Acuña left Saturday's game in the 2nd inning after pulling up halfway down the line on a grounder. He'd appeared in all 34 ATL games this season after being limited to 144 G across 2024-25 (post-ACL). Apr 24 2-run HR off Painter remains his last bomb.",
    form: 0,
    status: "il-10",
    injuryNote: "Grade 1 left hamstring strain (suffered in 2nd inning of 9-1 W at Coors, May 2). Placed on 10-day IL May 3, retroactive. Eli White / Jose Azocar absorb RF reps in his absence; return window unspecified but Grade 1 strains are typically 2-4 weeks.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/36185.png",
    assignment: "mlb",
    contract: { years: 8, total: 100000000, guaranteed: 100000000, apy: 12500000, throughYear: 2028 },
    career: [
      { years: "2018–", team: "Atlanta Braves", type: "MLB · 2023 NL MVP · 4x All-Star" },
    ],
  },
  {
    id: "olson",
    name: "Matt Olson",
    number: 28,
    position: "1B",
    positionGroup: "batter",
    lineupSpot: 2,
    bats: "L", throws: "R",
    nationality: "🇺🇸 USA", age: 32, experience: 10,
    stats: { avg: .302, obp: .372, slg: .647, ops: 1.019, hr: 13, rbi: 33, sb: 0, bb: 16, so: 38, games: 36, doubles: 3 },
    statNote: "BACK-TO-BACK BOMB NIGHTS, NOW NL-HR LEADER — Olson led off the 9th in Seattle with a 110-mph, 412-ft tiebreaking HR (#13, NL-leading) into the LCF seats off Mariners closer Andrés Muñoz on a 2-1 hung slider, lifting Atlanta to a 3-2 W. Two nights, two bombs after Monday's 428-ft 300th career off Logan Gilbert. He's now 301 career HR / 13 of 2026, slashing .302/.372/.647 with a 1.019 OPS and 33 RBI through 36 G — top-three in baseball by OPS. The Parkview HS (GA) product has been the single biggest swing in the lineup with Acuña on the IL.",
    form: 9.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/32767.png",
    assignment: "mlb",
    contract: { years: 8, total: 168000000, guaranteed: 168000000, apy: 21000000, throughYear: 2029 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2023 HR title (54)" },
      { years: "2016–2021", team: "Oakland Athletics", type: "MLB" },
    ],
  },
  {
    id: "riley",
    name: "Austin Riley",
    number: 27,
    position: "3B",
    positionGroup: "batter",
    lineupSpot: 3,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 29, experience: 8,
    stats: { avg: .197, obp: .280, slg: .343, ops: .623, hr: 5, rbi: 19, sb: 2, bb: 12, so: 36, games: 35 },
    statNote: "BAT QUIETER IN TUESDAY 3-2 W — no extra-base damage in Seattle as Kirby ground out 11 Braves; Atlanta managed 5 hits and the win came on Olson's 9th-inning leadoff HR. Riley still at .197/.280/.343 (.623 OPS), 5 HR / 19 RBI through 35 G. The pair of HRs over the weekend (Coors #4, Seattle Monday #5) is the encouraging look — the average has to climb, but the power signs are stacking up.",
    form: 8.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/34982.png",
    assignment: "mlb",
    contract: { years: 10, total: 212000000, guaranteed: 212000000, apy: 21200000, throughYear: 2032 },
    career: [
      { years: "2019–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2x Silver Slugger" },
    ],
  },
  {
    id: "ozuna",
    name: "Marcell Ozuna",
    number: 20,
    position: "DH",
    positionGroup: "batter",
    lineupSpot: 4,
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 35, experience: 13,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Left Braves in FA before 2026 — retained in data as historical reference only. See Baldwin/Yastrzemski for current DH reps.",
    form: 0,
    status: "departed",
    injuryNote: "Signed elsewhere in FA. Not on 2026 Braves roster.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/30205.png",
    assignment: "mlb",
    contract: null,
    career: [
      { years: "2020–2025", team: "Atlanta Braves", type: "MLB · 2023 WS · 2x All-Star" },
    ],
  },
  {
    id: "albies",
    name: "Ozzie Albies",
    number: 1,
    position: "2B",
    positionGroup: "batter",
    lineupSpot: 5,
    bats: "S", throws: "R",
    nationality: "🇨🇼 Curaçao", age: 29, experience: 9,
    stats: { avg: .314, obp: .360, slg: .538, ops: .898, hr: 8, rbi: 22, sb: 0, bb: 9, so: 19, games: 35, wOBA: .315, iso: .160 },
    statNote: "QUIET TUESDAY BUT THE 300 SETUP IS STILL THE STORY — Albies went 0-for-4 in the 3-2 W in Seattle as Kirby grounded out the heart of the order. The big swing of the series remains his Monday solo HR (#8) off Logan Gilbert that immediately preceded Olson's 300th. Slash dips slightly to .314/.360/.538 (.898 OPS), 8 HR / 22 RBI through 35 G — still very much locked in.",
    form: 9.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33783.png",
    assignment: "mlb",
    contract: { years: 7, total: 35000000, guaranteed: 35000000, apy: 5000000, throughYear: 2027 },
    career: [
      { years: "2017–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2021 WS champ" },
    ],
  },
  {
    id: "harris",
    name: "Michael Harris II",
    number: 23,
    position: "CF",
    positionGroup: "batter",
    lineupSpot: 6,
    bats: "L", throws: "R",
    nationality: "🇺🇸 USA", age: 25, experience: 5,
    stats: { avg: .322, obp: .357, slg: .561, ops: .918, hr: 7, rbi: 22, sb: 2, bb: 6, so: 18, games: 31, wrcPlus: null },
    statNote: "DH-ONLY USAGE THE NEXT WEEK — Walt Weiss confirmed Tuesday that Atlanta is committing Harris to DH/PH duty for ~7 days to let the left quad calm down rather than send him to the IL. The bat is too valuable to lose: .322/.357/.561 with 7 HR / 22 RBI in 31 G; pinch-hit go-ahead 2-run HR (#7) off Tyler Kinley capped Atlanta's 8-unanswered comeback at Coors Friday. The IL becomes the move only if the quad worsens.",
    form: 9.6,
    status: "day-to-day",
    injuryNote: "Left quad strain (originally Apr 23 vs WSH). Weiss announced May 5 the Braves will use Harris exclusively as DH or PH for the next ~week to let the leg heal — IL stint still possible if it doesn't progress. Eli White / Bairon Velandia / Azocar absorb CF reps in the meantime.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/42470.png",
    assignment: "mlb",
    contract: { years: 8, total: 72000000, guaranteed: 72000000, apy: 9000000, throughYear: 2030 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 2022 NL ROY · Gold Glove" },
    ],
  },
  {
    id: "baldwin",
    name: "Drake Baldwin",
    number: 55,
    position: "C",
    positionGroup: "batter",
    lineupSpot: 7,
    bats: "L", throws: "R",
    nationality: "🇺🇸 USA", age: 25, experience: 2,
    stats: { avg: .315, obp: .388, slg: .547, ops: .935, hr: 9, rbi: 30, sb: 1, bb: 14, so: 31, games: 35 },
    statNote: "BACK BEHIND THE DISH AS MURPHY EASES IN — Baldwin caught Elder's 9-K Tuesday gem and went 0-for-3, dropping the line to .315/.388/.547 (.935 OPS), 9 HR / 30 RBI through 35 G. Monday's leadoff HR (#9) off Gilbert is still the mark of the series. With Murphy back from the 60-day IL but on the bench Wednesday after going 0-for-3 Monday, Baldwin remains the primary catcher of a true tandem rather than a backup-now arrangement.",
    form: 9.3,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4810190.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB · 3rd-round 2022 draft (Missouri State)" },
    ],
  },
  {
    id: "profar",
    name: "Jurickson Profar",
    number: 7,
    position: "LF",
    positionGroup: "batter",
    lineupSpot: 8,
    bats: "S", throws: "R",
    nationality: "🇨🇼 Curaçao", age: 33, experience: 14,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Everyday LF in the post-Ozuna outfield rotation.",
    form: 6.9,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/31117.png",
    assignment: "mlb",
    contract: { years: 3, total: 42000000, guaranteed: 42000000, apy: 14000000, throughYear: 2027 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB · 2024 NL All-Star" },
      { years: "2012–2024", team: "Various (TEX, OAK, COL, SD)", type: "MLB" },
    ],
  },
  {
    id: "allen",
    name: "Nick Allen",
    number: 14,
    position: "SS",
    positionGroup: "batter",
    lineupSpot: 9,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 27, experience: 4,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Sharing SS reps with Dubón while Kim rehabs finger tendon. Defense-first profile.",
    form: 6.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40338.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB" },
      { years: "2022–2024", team: "Oakland Athletics", type: "MLB" },
    ],
  },
  {
    id: "yastrzemski",
    name: "Mike Yastrzemski",
    number: 5,
    position: "RF",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 35, experience: 8,
    stats: { avg: .209, obp: .280, slg: .275, ops: .555, hr: 0, rbi: 6, sb: 1, bb: 8, so: 25, games: 29 },
    statNote: "Offseason FA signing struggling out of the gate — .209/.280/.275, no HRs through 29 games. The error on Vierling's bullet through the LF gap on Apr 30 added the dagger run in the 5-2 L. Veteran platoon-piece role still intact while the bat looks for traction.",
    form: 5.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33341.png",
    assignment: "mlb",
    contract: { years: 1, total: 7000000, guaranteed: 7000000, apy: 7000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2019–2025", team: "San Francisco Giants", type: "MLB · 2021 NL All-Star" },
    ],
  },
  {
    id: "dubon",
    name: "Mauricio Dubón",
    number: 2,
    position: "UT",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇭🇳 Honduras", age: 31, experience: 8,
    stats: { avg: .283, obp: .332, slg: .455, ops: .787, hr: 2, rbi: 18, sb: 0, bb: 6, so: 20, games: 31, triples: 1 },
    statNote: "BASES-LOADED TRIPLE in the 8th at Coors Friday — the swing that finished erasing the 6-run hole and tied it 6-6 before Harris's 9th-inning HR sealed it. 2-for-5, 3 RBI on the night. Primary SS while Kim rehabs; rotates through 2B/LF/CF as needed. Now .283/.332/.455 with 18 RBI through 31 games.",
    form: 8.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/35304.png",
    assignment: "mlb",
    contract: { years: 2, total: 8500000, guaranteed: 8500000, apy: 4250000, throughYear: 2027 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2022–2025", team: "Houston Astros", type: "MLB · 2022 & 2023 WS champ" },
    ],
  },
  {
    id: "heim",
    name: "Jonah Heim",
    number: 28,
    position: "C",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "S", throws: "R",
    nationality: "🇺🇸 USA", age: 30, experience: 6,
    stats: { avg: .244, obp: .293, slg: .415, ops: .708, hr: 2, rbi: 9, sb: 0, bb: 4, so: 12, games: 12 },
    statNote: "DFA'd 24 HOURS AFTER A CAREER-HIGH 5 RBI — Heim was designated for assignment Monday May 4 when Sean Murphy was reinstated from the IL, then traded to the Athletics for cash considerations Tuesday May 5. The numbers tell the brutal story: a 5-RBI Sunday at Coors (#2 HR off Quintana, bases-loaded sac fly, 9th-inning 2-run double) didn't save him — Atlanta committed to a Baldwin-Murphy catching tandem the moment Murphy passed his rehab check. Final Atlanta line: .244/.293/.415, 2 HR / 9 RBI in 12 G. Off to Sacramento.",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd May 4, 2026 — traded to the Athletics for cash on May 5. No longer on the Braves 40-man roster.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33842.png",
    assignment: "mlb",
    contract: { years: 1, total: 1250000, guaranteed: 1250000, apy: 1250000, throughYear: 2026 },
    career: [
      { years: "2026", team: "Atlanta Braves", type: "MLB · 12 G" },
      { years: "2020–2025", team: "Texas Rangers", type: "MLB · 2023 WS champ · 2023 AL All-Star · Gold Glove" },
    ],
  },
  {
    id: "mateo",
    name: "Jorge Mateo",
    number: 3,
    position: "UT",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 30, experience: 5,
    stats: { avg: .286, obp: .318, slg: .476, ops: .794, hr: 2, rbi: 5, sb: 3, bb: 2, so: 10, games: 16, runs: 12, doubles: 2 },
    statNote: "2-RUN HR (#2) off Kyle Freeland in the 2nd of Sunday's 11-6 W — back-to-back with Jonah Heim's 420-ft blast on the same Quintana curve set. Speed/defense bench-piece signing has been a real asset behind Dubón at SS while Kim rehabs: .286/.318/.476 with 12 R / 5 RBI / 3 SB across 16 G. Plays every OF spot too.",
    form: 8.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33832.png",
    assignment: "mlb",
    contract: { years: 1, total: 1000000, guaranteed: 1000000, apy: 1000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2022–2025", team: "Baltimore Orioles", type: "MLB · 2023 ALDS run" },
      { years: "2021–2022", team: "San Diego Padres", type: "MLB" },
    ],
  },
  {
    id: "jarvis",
    name: "Jim Jarvis",
    number: 5,
    position: "UT",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 25, experience: 0,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "MLB DEBUT MAY 6 — Atlanta selected Jarvis from Triple-A Gwinnett (Azocar DFA'd in the corresponding move) and slotted him in at SS batting 9th to give Mateo a day off. The 25-year-old Alabama product was an 11th-round 2023 Tigers pick before being traded to Atlanta at the 2025 deadline (for Rafael Montero). He was raking at Gwinnett: .305/.418/.445 with 4 HR / 15 SB across 33 G — and projects as a versatile utility infielder (SS/2B/3B) rather than a one-spot regular.",
    form: 7.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5205951.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · debut May 6, 2026" },
      { years: "2025", team: "Atlanta org", type: "Acquired from DET 7/30/25 in Rafael Montero trade" },
      { years: "2023–2025", team: "Detroit Tigers org", type: "11th round, 2023 (Alabama)" },
    ],
  },
  {
    id: "azocar",
    name: "José Azocar",
    number: 17,
    position: "OF",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 30, experience: 5,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "DFA'd MAY 6 — Atlanta designated Azocar for assignment to clear the spot for IF Jim Jarvis's MLB debut. Just three days after being selected from Triple-A Gwinnett (May 3) to fill Acuña's roster spot, the speed/defense fourth-outfielder is on the wire. Likely outcome: outright to Triple-A within 5 days, possibly traded for cash.",
    form: 6.0,
    status: "departed",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/35058.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2025", team: "New York Mets", type: "MLB" },
      { years: "2022–2024", team: "San Diego Padres", type: "MLB · debut 2022" },
    ],
  },

  // ── STARTING ROTATION ───────────────────────────────────────────────────────
  {
    id: "sale",
    name: "Chris Sale",
    number: 51,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 1,
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 37, experience: 15,
    stats: { era: 2.14, whip: 0.83, ip: 42.0, k: 49, bb: 9, hr: null, w: 6, l: 1, games: 7, starts: 7 },
    statNote: "MLB-LEADING 6th W — Sale dominated at altitude Saturday: 7 IP / 3 H / 1 ER / 11 K in the 9-1 rout at Coors. Season line down to 2.14 ERA / 0.83 WHIP across 7 starts; the 49 K leads the NL. Coors as a tune-up for the Strider series finale Sunday. 150th career W in the bag (Apr 26 vs PHI), already past Glavine on the all-time K list (2,608+).",
    form: 9.7,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/30948.png",
    assignment: "mlb",
    contract: { years: 2, total: 54000000, guaranteed: 38000000, apy: 27000000, throughYear: 2027 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB · 2024 NL Cy Young" },
      { years: "2016–2023", team: "Boston Red Sox", type: "MLB · 2018 WS champ" },
      { years: "2010–2016", team: "Chicago White Sox", type: "MLB · 7x All-Star" },
    ],
  },
  {
    id: "lopez",
    name: "Reynaldo López",
    number: 40,
    position: "RP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 32, experience: 10,
    stats: { era: 3.42, whip: 1.31, ip: 23.2, k: 22, bb: 11, hr: null, w: 2, l: 1, games: 6, starts: 5 },
    statNote: "Picked up the W (now 2-1, ERA down to 3.27) in Wednesday's 4-3 walk-off over DET — 2 scoreless / 0 H / 2 K out of the bullpen in the 8th and 9th, setting up Olson's walk-off blast. Second pen outing of the Walt Weiss reset (Apr 27) and a clear sign the slider work is taking. Weiss has said López projects back to the rotation once the mechanical reset is done.",
    form: 7.2,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33860.png",
    assignment: "mlb",
    contract: { years: 3, total: 30000000, guaranteed: 30000000, apy: 10000000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB · 2024 NL All-Star" },
      { years: "2018–2023", team: "Chicago White Sox", type: "MLB" },
    ],
  },
  {
    id: "holmes",
    name: "Grant Holmes",
    number: 58,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 3,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 30, experience: 3,
    stats: { era: 4.50, whip: 1.40, ip: 36.1, k: 27, bb: 17, w: 2, l: 1, games: 7, starts: 7 },
    statNote: "Got bullied by altitude Friday — 4 IP / 6 H / 4 ER / 3 BB / 2 K, ND in Atlanta's 8-6 comeback W. Quintana matched zeroes through 4 (Holmes left trailing 4-0); the Braves' bullpen and offense bailed him out. ERA up to 4.50 across 7 starts, but the rotation depth absorbs the bad start. Apr 24 W vs PHI (6 IP, 2 ER) still the line-of-the-month for him.",
    form: 7.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33840.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "elder",
    name: "Bryce Elder",
    number: 55,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 4,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 27, experience: 4,
    stats: { era: 2.02, whip: 1.06, ip: 49.0, k: 45, bb: 16, w: 3, l: 1, games: 8, starts: 8 },
    statNote: "9-K MASTERPIECE IN SEATTLE — Tuesday: 6 IP / 2 H / 2 ER / 3 BB / 9 K (season-high K total), 78 pitches / 51 strikes, ND in Atlanta's 3-2 W after the offense was held in check by Kirby. The two earned came on a Cal Raleigh solo HR; otherwise Elder twirled a chess match against Seattle's contact-heavy lineup. ERA ticks up to 2.02 across 8 starts, but the strike-throwing version is the rotation's most consistent piece behind Sale.",
    form: 8.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4301067.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 2023 NL All-Star" },
    ],
  },
  {
    id: "suarez-jose",
    name: "José Suárez",
    number: 49,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 5,
    bats: "L", throws: "L",
    nationality: "🇻🇪 Venezuela", age: 28, experience: 7,
    stats: { era: 6.61, whip: 2.08, ip: 16.1, k: 21, bb: 12, w: 0, l: 1, games: 8, starts: 1 },
    statNote: "Designated for assignment May 1 in the corresponding move when Hunter Stratton was recalled. Out of minor-league options, 6.61 ERA across 8 G / 16.1 IP. Took the LP in both the Apr 25 (10) walk-off vs PHI and the Apr 30 5-2 finale vs DET (walked two in the 9th).",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd May 1, 2026 — off the 40-man.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40981.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2019–2025", team: "Los Angeles Angels", type: "MLB" },
    ],
  },
  {
    id: "perez-martin",
    name: "Martín Pérez",
    number: 54,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 6,
    bats: "L", throws: "L",
    nationality: "🇻🇪 Venezuela", age: 35, experience: 14,
    stats: { era: 2.38, whip: 1.03, ip: 34.0, k: 24, bb: 12, w: 2, l: 2, games: 7, starts: 5 },
    statNote: "PRESSED INTO SERVICE WEDNESDAY, TOUGH-LUCK L (2-2) — Pérez took the rubber-match start in Seattle on short turn (5 days) and was solid: 5.2 IP / 5 H / 2 ER / 3 BB / 5 K, but Atlanta managed just 4 hits and 1 run for him. Cole Young's RBI double in the 3rd off a 6-4-3 DP set the tone; Julio Rodríguez's solo HR in the 6th was the killer. ERA up slightly to 2.38; pen-day-style usage may continue if Strider's next outing slots in around the LAD series.",
    form: 7.6,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/31098.png",
    assignment: "mlb",
    contract: { years: 1, total: 2000000, guaranteed: 0, apy: 2000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · 2022 AL All-Star" },
      { years: "2012–2025", team: "Various (TEX, BOS, MIN, PIT, CHW)", type: "MLB" },
    ],
  },
  {
    id: "ritchie",
    name: "JR Ritchie",
    number: 48,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 7,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 22, experience: 0,
    stats: { era: 3.63, whip: 1.50, ip: 17.1, k: 13, bb: 12, w: 1, l: 0, games: 3, starts: 3 },
    statNote: "HOMECOMING WITH GROWING PAINS — Seattle native Ritchie battled command in front of family at T-Mobile Park: 5 IP / 4 H / 3 ER / 6 BB / 2 K, ND in Atlanta's 5-4 L. Threw just 47 of 93 pitches for strikes; opened the 6th by walking the first two batters before serving up a 3-run HR to Luke Raley. Crawford's 2-run go-ahead HR off the bullpen in the bottom of the 6th flipped the 4-0 lead. ERA up to 3.63, WHIP 1.50 over 17.1 IP. Debut Apr 23 at WSH (7 IP / 2 ER / 7 K) is still the line-of-the-month for him.",
    form: 7.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5080757.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · MLB debut Apr 23, 2026" },
    ],
  },

  // ── BULLPEN ─────────────────────────────────────────────────────────────────
  {
    id: "iglesias",
    name: "Raisel Iglesias",
    number: 26,
    position: "CP",
    positionGroup: "pitcher",
    bullpenRole: "closer",
    bats: "R", throws: "R",
    nationality: "🇨🇺 Cuba", age: 36, experience: 11,
    stats: { era: 0.00, whip: 0.62, ip: 9.2, k: 12, bb: 1, sv: 6, hold: null, games: 9 },
    statNote: "ACTIVATED AND IMMEDIATELY BACK IN THE 9TH — Iglesias was reinstated from the 15-day IL Tuesday morning (Carrasco DFA'd in the corresponding move), then closed out the 3-2 W in Seattle for his 6th save in his first appearance back. Spotless line now: 0.00 ERA, 0.62 WHIP, 5 H / 12 K / 1 BB across 9.2 IP. Robert Suarez slides back into a setup look (took the W Tuesday, 3-0).",
    form: 7.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33618.png",
    assignment: "mlb",
    contract: { years: 1, total: 16000000, guaranteed: 16000000, apy: 16000000, throughYear: 2026 },
    career: [
      { years: "2022–", team: "Atlanta Braves", type: "MLB · 3x 30-save season" },
    ],
  },
  {
    id: "suarez-robert",
    name: "Robert Suarez",
    number: 75,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "closer",
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 35, experience: 4,
    stats: { era: 0.66, whip: 0.81, ip: 13.2, k: 14, bb: 2, sv: 3, hold: 1, games: 14, w: 3, l: 0 },
    statNote: "FILLED IN AS CLOSER, NOW BACK TO SETUP — Suarez (W, 3-0) tossed a clean 8th in the 3-2 W in Seattle to bridge to Iglesias's return; he had been spotless during Iglesias's IL stint (3 SV / 0.66 ERA / 14:2 K:BB across 13.2 IP) and is now the team's premier setup arm with a closer-quality profile.",
    form: 8.7,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4148749.png",
    assignment: "mlb",
    contract: { years: 3, total: 45000000, guaranteed: 45000000, apy: 15000000, throughYear: 2028 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · 2x All-Star" },
      { years: "2022–2025", team: "San Diego Padres", type: "MLB" },
    ],
  },
  {
    id: "bummer",
    name: "Aaron Bummer",
    number: 48,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "lhp",
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 32, experience: 9,
    stats: { era: 4.35, whip: 1.36, ip: 10.1, k: 8, bb: 4, sv: 0, hold: null, games: 14, w: 0, l: 1 },
    statNote: "LH specialist — 14 G, 10.1 IP, 4.35 ERA. Walked McGonigle in relief Thu in DET's 5-2 sweep-avoiding W; the sac fly that followed went on the books as the go-ahead run. Still a high-leverage piece, but the recent results haven't matched the 98-game ATL track record.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/36131.png",
    assignment: "mlb",
    contract: { years: 2, total: 13000000, guaranteed: 13000000, apy: 6500000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
      { years: "2017–2023", team: "Chicago White Sox", type: "MLB" },
    ],
  },
  {
    id: "lee",
    name: "Dylan Lee",
    number: 52,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "lhp",
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 31, experience: 5,
    stats: { era: 1.23, whip: 0.55, ip: 14.2, k: 17, bb: 2, sv: 0, hold: null, games: 15, w: 1, l: 0 },
    statNote: "Quietly the best arm in the pen — 15 G, 1.23 ERA, 0.55 WHIP, 17 K against just 2 BB across 14.2 IP. Took the 8th in Saturday's loss vs PHI (Schwarber leadoff triple, Harper sac fly) but otherwise lights-out. Top lefty in the pen and still the highest-WAR arm among the Lee/Bummer/Kinley trio.",
    form: 6.4,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/41455.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2021–", team: "Atlanta Braves", type: "MLB · 2021 WS champ" },
    ],
  },
  {
    id: "kinley",
    name: "Tyler Kinley",
    number: 58,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 35, experience: 7,
    stats: { era: 1.29, whip: 1.14, ip: 14.0, k: 14, bb: 7, sv: 0, hold: null, games: 15, w: 3, l: 1 },
    statNote: "Hard-slider middle-relief arm — 15 G, 1.29 ERA, 14 K / 14 IP. Already 3-1 from middle relief; the offseason signing has been the biggest non-Suarez bullpen value-add of the year.",
    form: 6.8,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/34166.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2020–2025", team: "Colorado Rockies", type: "MLB" },
    ],
  },
  {
    id: "payamps",
    name: "Joel Payamps",
    number: 37,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 31, experience: 6,
    stats: { era: 8.22, whip: 1.70, ip: 7.2, k: 9, bb: 4, sv: 0, hold: null, games: 12, w: 0, l: 2 },
    statNote: "Designated for assignment May 1 alongside José Suárez when Stratton/Molina came up. Out of minor-league options. The Apr 30 lead-loss vs DET (Carpenter triple, Vierling double, walk to McGonigle) was his last Atlanta outing — 8.22 ERA across 12 G / 7.2 IP. The strike-thrower profile flashed (9 K) but the leverage trust never came back after April.",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd May 1, 2026 — off the 40-man.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40021.png",
    assignment: "mlb",
    contract: { years: 1, total: 3000000, guaranteed: 3000000, apy: 3000000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2023–2025", team: "Milwaukee Brewers", type: "MLB" },
    ],
  },
  {
    id: "hamilton",
    name: "Ian Hamilton",
    number: 71,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 31, experience: 5,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Designated for assignment Apr 22 to clear a roster spot for Didier Fuentes' spot start. Off the 40-man.",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd Apr 22, 2026 — no longer on the Braves 40-man roster.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/41127.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2023–2025", team: "New York Yankees", type: "MLB" },
    ],
  },
  {
    id: "fuentes",
    name: "Didier Fuentes",
    number: 68,
    position: "SP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "R", throws: "R",
    nationality: "🇨🇴 Colombia", age: 20, experience: 1,
    stats: { era: 4.09, whip: 1.18, ip: 11.0, k: 14, bb: 3, sv: 0, hold: null, games: 4, starts: 1, w: 1, l: 0 },
    statNote: "FIRST CAREER WIN — 2 scoreless out of the pen in Friday's 8-6 comeback at Coors (5th-6th, 3 K, 1 H), inheriting and stranding a runner before Atlanta erupted for 8 unanswered. The 20-year-old (youngest SP in the majors) keeps cementing the long-relief / emergency-start role behind the bullpen. Apr 22 spot start vs WSH: 3 IP / 7 H / 4 ER (Braves still won 8-6).",
    form: 8.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5291189.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB · MLB debut" },
    ],
  },
  {
    id: "dodd",
    name: "Dylan Dodd",
    number: 64,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 28, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "REHAB ASSIGNMENT BEGINS — Atlanta announced Tuesday May 5 that Dodd will start a rehab assignment with Triple-A Gwinnett (left thoracic spine inflammation since Apr 23). If it goes cleanly, the LH long man could rejoin the bullpen by Friday's series opener at Truist vs LAD, restoring a third lefty alongside Bummer and Lee.",
    form: 0,
    status: "il-15",
    injuryNote: "Left thoracic spine inflammation. 15-day IL since Apr 23. Triple-A Gwinnett rehab assignment began May 5; possible activation by the Friday LAD series opener.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4416462.png",
    assignment: "rehab",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "carrasco",
    name: "Carlos Carrasco",
    number: 59,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 39, experience: 16,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "DFA'd AGAIN MAY 5 — third time this season Atlanta has cut Carrasco loose, this time to make 40-man room for Iglesias's IL activation. Logged 2.1 IP / 1 H / 0 ER / 2 K across two games during his most recent stint after re-signing in mid-April. At 39 he's a strong bet to pass through waivers and re-sign with Gwinnett yet again.",
    form: 0,
    status: "departed",
    injuryNote: "DFA'd May 5, 2026 — off the 40-man roster (third DFA this season; expected to clear waivers and re-sign with Triple-A Gwinnett).",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/30976.png",
    assignment: "mlb",
    contract: { years: 1, total: 1500000, guaranteed: 0, apy: 1500000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB (2nd stint)" },
      { years: "2009–2024", team: "Various (CLE, NYM, NYY)", type: "MLB · 2017 AL 18-win season" },
    ],
  },
  {
    id: "stratton",
    name: "Hunter Stratton",
    number: 65,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 29, experience: 3,
    stats: { era: 4.50, whip: 1.92, ip: 12.0, k: 18, bb: 5, sv: 0, hold: null, games: 11, w: 2, l: 2 },
    statNote: "OPTIONED BACK to Triple-A Gwinnett following Saturday night's win — the corresponding move that cleared a roster spot for Spencer Strider's Sunday activation. Three-day big-league cameo this trip with no game appearance. Power righty acquired from Pittsburgh in July 2025 (for Titus Dumitru); the Achilles/knee rehab is finished and he sits as the next-up bullpen arm at Gwinnett.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4987652.png",
    assignment: "aaa",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB" },
      { years: "2023–2025", team: "Pittsburgh Pirates", type: "MLB · debut 2023" },
    ],
  },
  {
    id: "molina-anthony",
    name: "Anthony Molina",
    number: 67,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "long",
    bats: "R", throws: "R",
    nationality: "🇻🇪 Venezuela", age: 24, experience: 2,
    stats: { era: 4.50, whip: 1.36, ip: 14.0, k: 10, bb: 3, sv: 0, hold: null, games: 5, starts: 2, w: 1, l: 2 },
    statNote: "CONTRACT SELECTED MAY 1 from Triple-A Gwinnett alongside Stratton's recall. Four-pitch strike-thrower (4-seam, slider, change, two-seam) claimed off waivers from Colorado in December 2025. Made his MLB debut as a Rule 5 pick on 2024 Opening Day with COL (35 G, 6.79 ERA). Adds long-relief / spot-start depth behind the bullpen with Suárez and Payamps gone.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5016983.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2024–2025", team: "Colorado Rockies", type: "MLB · Rule 5 pick from TB 2023" },
    ],
  },

  // ── TRIPLE-A DEPTH (recall candidates on 40-man, optioned to Gwinnett) ─────
  {
    id: "munoz-rolddy",
    name: "Rolddy Muñoz",
    number: 78,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: "middle",
    bats: "R", throws: "R",
    nationality: "🇩🇴 Dominican Republic", age: 26, experience: 2,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Power righty — 97-98 mph FB, slider-heavy. 7.2 scoreless IP / 7 K through first 5 at Gwinnett. Optioned back down when Dodd was recalled Apr 21; next man up in a bullpen emergency.",
    form: 6.5,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/5131982.png",
    assignment: "aaa",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2025–", team: "Atlanta Braves", type: "MLB · MLB debut 2025" },
    ],
  },

  // ── INJURED LIST ────────────────────────────────────────────────────────────
  {
    id: "strider",
    name: "Spencer Strider",
    number: 99,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: 2,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 27, experience: 5,
    stats: { era: 8.10, whip: 2.70, ip: 3.1, k: 6, bb: 5, w: 0, l: 0, games: 1, starts: 1 },
    statNote: "ROCKY 2026 DEBUT at Coors — 3.1 IP / 4 H / 3 ER / 5 BB / 6 K, ND in Atlanta's 11-6 sweep-clinching W. TJ Rumfield led off the 3rd with a 423-ft HR; the five walks tied a career high (also at Coors, June 4 2022). Faced 19 batters with 12 'three-true-outcome' results — stuff was there (96+ FB) but command lagged after the long layoff. Strider's own assessment was characteristically blunt; first big-league outing since the spring oblique strain. Next turn lined up vs SEA on the road.",
    form: 6.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4307825.png",
    assignment: "mlb",
    contract: { years: 6, total: 75000000, guaranteed: 75000000, apy: 12500000, throughYear: 2028 },
    career: [
      { years: "2021–", team: "Atlanta Braves", type: "MLB · 2x All-Star · 2023 NL Ks leader" },
    ],
  },
  {
    id: "murphy",
    name: "Sean Murphy",
    number: 12,
    position: "C",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 31, experience: 7,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "BENCH WEDNESDAY AS THE TEAM EASES HIM BACK — Murphy went 0-for-3 with two K's in his Monday season debut catching Ritchie; Atlanta keeps him on the bench Wednesday in Seattle and will phase him in around hip-surgery recovery rather than rush a 50/50 split with Baldwin from Day 1. He hit .333 (8-for-24) at Gwinnett with 2 doubles, 4 RBI, 6 R, and a 6-game on-base streak before activation. The catching room is officially Baldwin-first, Murphy-rebuilding through May.",
    form: 7.0,
    status: "active",
    injuryNote: null,
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33557.png",
    assignment: "mlb",
    contract: { years: 6, total: 73000000, guaranteed: 73000000, apy: 12166666, throughYear: 2028 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB · 2023 NL All-Star · Gold Glove" },
      { years: "2019–2022", team: "Oakland Athletics", type: "MLB" },
    ],
  },
  {
    id: "kim",
    name: "Ha-Seong Kim",
    number: 7,
    position: "SS",
    positionGroup: "batter",
    lineupSpot: null,
    bats: "R", throws: "R",
    nationality: "🇰🇷 South Korea", age: 30, experience: 5,
    stats: { avg: null, obp: null, slg: null, ops: null, hr: null, rbi: null, games: null },
    statNote: "Officially began his major-league rehab assignment Tuesday (Apr 28) with the Double-A Columbus Clingstones — the first MLB rehab assignment in Clingstones franchise history. Walt Weiss said pre-game that Kim will need \"a couple of weeks\" of at-bats before the Braves consider promoting him; mid-May target for the Atlanta debut still holds.",
    form: 0,
    status: "il-60",
    injuryNote: "Torn tendon right middle finger (Jan 2026 surgery — slipped on ice in South Korea). Rehab assignment underway at Double-A Columbus (six-game homestand vs Montgomery opened Apr 28). \"A couple of weeks\" timetable per Weiss; mid-May Atlanta target.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4089862.png",
    assignment: "rehab",
    contract: { years: 2, total: 24000000, guaranteed: 24000000, apy: 12000000, throughYear: 2027 },
    career: [
      { years: "2026–", team: "Atlanta Braves", type: "MLB" },
      { years: "2021–2025", team: "San Diego Padres", type: "MLB · Gold Glove" },
    ],
  },
  {
    id: "smith-shawver",
    name: "AJ Smith-Shawver",
    number: 60,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 23, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, w: null, l: null, games: null, starts: null },
    statNote: "Tommy John June 2025 — return window 2026 or 2027 season.",
    form: 0,
    status: "il-60",
    injuryNote: "Tommy John surgery (Jun 2025). Return: late 2026 or 2027.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4917640.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "waldrep",
    name: "Hurston Waldrep",
    number: 66,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 24, experience: 2,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, w: null, l: null, games: null, starts: null },
    statNote: "Set to throw his first bullpen session this week — Walt Weiss confirmed pre-game Apr 28. Targeted return remains June for game action.",
    form: 0,
    status: "il-60",
    injuryNote: "Right elbow inflammation; post-arthroscopic surgery Feb 23. First post-surgery bullpen session scheduled for this week (per Weiss, Apr 28). Targeted return: June.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4740117.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB · 2023 R1 pick" },
    ],
  },
  {
    id: "schwellenbach",
    name: "Spencer Schwellenbach",
    number: 56,
    position: "SP",
    positionGroup: "pitcher",
    rotationSpot: null,
    bats: "R", throws: "R",
    nationality: "🇺🇸 USA", age: 26, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, w: null, l: null, games: null, starts: null },
    statNote: "Recovering from offseason arthroscopic elbow surgery.",
    form: 0,
    status: "il-60",
    injuryNote: "Arthroscopic elbow surgery. Targeted return: late June / July.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/4424862.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
  {
    id: "jimenez",
    name: "Joe Jiménez",
    number: 77,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: null,
    bats: "R", throws: "R",
    nationality: "🇵🇷 Puerto Rico", age: 31, experience: 9,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Knee surgery — no timetable.",
    form: 0,
    status: "il-60",
    injuryNote: "Left knee surgery. No timetable for return.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/33760.png",
    assignment: "mlb",
    contract: { years: 3, total: 26000000, guaranteed: 26000000, apy: 8666666, throughYear: 2026 },
    career: [
      { years: "2023–", team: "Atlanta Braves", type: "MLB · 2018 AL All-Star" },
    ],
  },
  {
    id: "young",
    name: "Danny Young",
    number: 69,
    position: "RP",
    positionGroup: "pitcher",
    bullpenRole: null,
    bats: "L", throws: "L",
    nationality: "🇺🇸 USA", age: 30, experience: 3,
    stats: { era: null, whip: null, ip: null, k: null, bb: null, sv: null, hold: null, games: null },
    statNote: "Transferred to 60-day IL Apr 11. Could return after the All-Star break.",
    form: 0,
    status: "il-60",
    injuryNote: "Tommy John (May 2025). Transferred to 60-day IL Apr 11.",
    image: "https://a.espncdn.com/i/headshots/mlb/players/full/40903.png",
    assignment: "mlb",
    contract: { years: 1, total: 760000, guaranteed: 0, apy: 760000, throughYear: 2026 },
    career: [
      { years: "2024–", team: "Atlanta Braves", type: "MLB" },
    ],
  },
];

// ─── RSS FEEDS (news pipeline) ─────────────────────────────────────────────────
export const RSS_FEEDS = [
  {
    name: "MLB.com Braves",
    url: "https://www.mlb.com/braves/feeds/news/rss.xml",
    category: "official",
  },
  {
    name: "Battery Power",
    url: "https://www.batterypower.com/rss/index.xml",
    category: "fan",
  },
  {
    name: "AJC Braves",
    url: "https://www.ajc.com/arc/outboundfeeds/rss/section/sports/braves/",
    category: "major",
  },
  {
    name: "MLB Trade Rumors – Braves",
    url: "https://www.mlbtraderumors.com/atlanta-braves/feed",
    category: "major",
  },
  {
    name: "Talking Chop",
    url: "https://www.talkingchop.com/rss/index.xml",
    category: "fan",
  },
];

// ─── TEAM LOGOS (NL East + recent opponents) ────────────────────────────────────
export const TEAM_LOGOS = {
  ATL: "https://a.espncdn.com/i/teamlogos/mlb/500/atl.png",
  PHI: "https://a.espncdn.com/i/teamlogos/mlb/500/phi.png",
  NYM: "https://a.espncdn.com/i/teamlogos/mlb/500/nym.png",
  WSH: "https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png",
  MIA: "https://a.espncdn.com/i/teamlogos/mlb/500/mia.png",
  KC:  "https://a.espncdn.com/i/teamlogos/mlb/500/kc.png",
  LAD: "https://a.espncdn.com/i/teamlogos/mlb/500/lad.png",
  SD:  "https://a.espncdn.com/i/teamlogos/mlb/500/sd.png",
  NYY: "https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png",
  HOU: "https://a.espncdn.com/i/teamlogos/mlb/500/hou.png",
};

// ─── UPCOMING SCHEDULE ─────────────────────────────────────────────────────────
// The next ~5 scheduled games used by the rotation map / probable-pitchers strip.
// Skill maintains this each daily run: drop today's game once it moves to RESULTS,
// add a new tail entry. atlSP.id should match a PLAYERS entry so the avatar can
// render; use null for true TBAs. daysRest is calendar days since last MLB start.
export const UPCOMING_SCHEDULE = [
  {
    date: "2026-05-08",
    weekday: "Fri",
    time: "10:10 PM ET",
    opp: "LAD",
    home: false,
    venue: "Dodger Stadium",
    atlSP: { id: "sale", name: "Chris Sale", record: "6-1", era: 2.14, daysRest: 6, hand: "L" },
    oppSP: { name: "Emmet Sheehan", record: null, era: null, hand: "R" },
    note: "MARQUEE SERIES OPENER AT CHAVEZ RAVINE — Sale (4-game personal W streak) vs Sheehan (coming off a 4-ER L in St. Louis with 8 K, 0 BB) · ATL's first West Coast night-cap of the year",
  },
  {
    date: "2026-05-09",
    weekday: "Sat",
    time: "9:10 PM ET",
    opp: "LAD",
    home: false,
    venue: "Dodger Stadium",
    atlSP: { id: "ritchie", name: "JR Ritchie", record: "1-0", era: 3.63, daysRest: 4, hand: "R" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Ritchie back on the bump after the Seattle homecoming wobble · LAD middle game",
  },
  {
    date: "2026-05-10",
    weekday: "Sun",
    time: "4:10 PM ET",
    opp: "LAD",
    home: false,
    venue: "Dodger Stadium",
    atlSP: { id: "elder", name: "Bryce Elder", record: "3-1", era: 2.02, daysRest: 5, hand: "R" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Elder on regular rest after the 9-K Seattle masterpiece · LAD series finale · Mother's Day matinee on the West Coast",
  },
  {
    date: "2026-05-12",
    weekday: "Tue",
    time: "7:20 PM ET",
    opp: "WSH",
    home: true,
    venue: "Truist Park",
    atlSP: { id: "holmes", name: "Grant Holmes", record: "2-1", era: 4.50, daysRest: 11, hand: "R" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Truist HOMESTAND OPENER vs WSH — Holmes finally gets the ball after Pérez was bumped up to start in Seattle Wed · 11 days since Holmes's last MLB outing (Coors May 1)",
  },
  {
    date: "2026-05-13",
    weekday: "Wed",
    time: "7:20 PM ET",
    opp: "WSH",
    home: true,
    venue: "Truist Park",
    atlSP: { id: "strider", name: "Spencer Strider", record: "0-0", era: 8.10, daysRest: 10, hand: "R" },
    oppSP: { name: "TBA", record: null, era: null, hand: null },
    note: "Strider's 2nd start of 2026 after the rocky 3.1-IP Coors debut May 3 · sea-level Truist a much friendlier test",
  },
];

// ─── NEXT GAME ──────────────────────────────────────────────────────────────────
export const NEXT_GAME = {
  date: "2026-05-08",
  time: "10:10 PM ET",
  opp: "LAD",
  home: false,
  venue: "Dodger Stadium · Los Angeles, CA",
  tv: "FanDuel Sports Network Southeast",
  probables: {
    atl: { pitcher: "Chris Sale", record: "6-1", era: 2.14 },
    opp: { pitcher: "Emmet Sheehan", record: null, era: null },
  },
  note: "MARQUEE OPENER AT CHAVEZ RAVINE — Atlanta (26-12) flies west off a Wednesday loss in Seattle and a Thursday travel day for a three-game showdown vs the defending-champion Dodgers. Chris Sale (6-1, 2.14, NL-leading 49 K) starts on his regular turn after the 11-K Coors gem; he carries a personal four-game W streak into LA. Emmet Sheehan goes for the Dodgers, coming off a tough 4-ER (2 HR) L in St. Louis with 8 K and 0 BB. Acuña stays on the 10-day IL; Harris remains DH-only; Murphy continues to ease back in after the 60-day-IL recovery; Iglesias secured his 6th save Tuesday in his first outing back. Jim Jarvis (called up Wed for his MLB debut) provides middle-IF cover with Mateo. First pitch on the West Coast feels late but it's a 7:10 local — ATL's marketed get-the-DVR-ready broadcast.",
};

// ─── RECENT RESULTS ─────────────────────────────────────────────────────────────
export const RESULTS = [
  { date: "2026-05-06", opp: "SEA", home: false, atlScore: 1, oppScore: 3, result: "L", note: "FIRST SERIES LOSS OF 2026 — Bryan Woo (W, 2-2) shut Atlanta down in the rubber match: 6 IP / 1 H / 2 BB / 9 K (tied his season-high) on a season-high 98 pitches (66 strikes). Mauricio Dubón's two-out single in the 4th was the Braves' ONLY hit off Woo; ATL finished with 4 H, 2 BB, and 12 K total. Pereda led off the 3rd with a single, Leo Rivas doubled, and J.P. Crawford walked to load the bases — Cal Raleigh's 6-4-3 DP scored the first run, and Cole Young (3-for-4, 2 doubles) added an RBI 2B in the same inning. Julio Rodríguez crushed a solo HR (#5) in the 6th off Pérez. José Ferrer pitched a 1-2-3 9th for his 2nd save. Martín Pérez (LP, 2-2): 5.2 IP / 5 H / 2 ER / 3 BB / 5 K — quality start wasted. Atlanta drops to 26-12; the eight-series win streak (and 10-0-1 series mark to open the year) is over. Pregame roster move: SS/IF JIM JARVIS selected from Triple-A Gwinnett for his MLB debut (started SS, batted 9th); José Azocar DFA'd in the corresponding move." },
  { date: "2026-05-05", opp: "SEA", home: false, atlScore: 3, oppScore: 2, result: "W", note: "OLSON WALKS BACK SEATTLE — Matt Olson led off the 9th with a 110-mph, 412-ft tiebreaking HR (NL-leading #13) into the LCF seats off Mariners closer Andrés Muñoz on a hung 2-1 slider, lifting Atlanta past Seattle 3-2 and to 26-11. Bryce Elder (ND): 6 IP / 2 H / 2 ER / 3 BB / 9 K (season-high) — only blemish a Cal Raleigh solo HR. George Kirby (ND for SEA): 7 IP / 5 H / 2 ER / 1 BB / 5 K. Robert Suarez (W, 3-0) tossed a clean 8th. Pre-game roster moves: Raisel Iglesias activated from the 15-day IL (Carrasco DFA'd in the corresponding move); Iglesias closed the 9th for his 6th save in his first appearance back. Dylan Dodd began a Triple-A Gwinnett rehab assignment; he could rejoin the bullpen by Friday's LAD opener. Walt Weiss also confirmed Michael Harris II will be DH-only for the next ~week to nurse the left quad without an IL trip." },
  { date: "2026-05-04", opp: "SEA", home: false, atlScore: 4, oppScore: 5, result: "L", note: "MARINERS WALK BACK A 4-0 LEAD — Atlanta jumped Logan Gilbert with FOUR solo HRs (Drake Baldwin leadoff to CF, Albies and Olson back-to-back to start the 6th, Austin Riley right after) — but Olson's blast was historic on its own: a 428-ft shot to LCF that made him the 166th player to 300 career home runs. Then the bottom of the 6th unspooled it: JR Ritchie (ND) walked the first two and Luke Raley turned on a 3-run HR; Crawford added a go-ahead 2-run HR off the pen for the 5-4 lead Seattle never gave back. Final pitching line for Ritchie: 5 IP / 4 H / 3 ER / 6 BB / 2 K (47-of-93 strikes). Atlanta drops to 25-11, ending a 3-game W streak. Pregame: Sean Murphy reinstated from the 60-day IL after his Gwinnett rehab (.333 / 4 RBI); Jonah Heim DFA'd in the corresponding move. (Heim later traded to OAK for cash Tuesday.)" },
  { date: "2026-05-03", opp: "COL", home: false, atlScore: 11, oppScore: 6, result: "W", note: "SWEEP COMPLETE, STRIDER SURVIVES — Atlanta's offense bailed out a rocky 2026 debut from Spencer Strider in an 11-6 series-clinching win at Coors. Strider (ND): 3.1 IP / 4 H / 3 ER / 5 BB / 6 K, gave up a 423-ft leadoff HR to TJ Rumfield in the 3rd; the five walks tied a career high. JONAH HEIM was the headline bat: career-high-tying 5 RBI on a 2nd-inning 420-ft HR off Quintana (back-to-back with Jorge Mateo's #2), a bases-loaded sac fly in the 5th, and a 2-out 2-run double in the 9th. Mateo's 2-run HR. Atlanta now 25-10 — the franchise's best 35-game start in 134 years, best in the modern era. Pregame: Acuña placed on the 10-day IL with a Grade 1 hamstring strain (MRI), Azocar selected from Triple-A Gwinnett; Stratton optioned to Gwinnett (Sat night) to clear the spot for Strider's activation." },
  { date: "2026-05-02", opp: "COL", home: false, atlScore: 9, oppScore: 1, result: "W", note: "SALE DOMINATES AT ALTITUDE, BALDWIN ALMOST CYCLES — Atlanta's MLB-best record climbs to 24-10 in a 9-1 rout at Coors. Chris Sale (W, 6-1) was masterful: 7 IP / 3 H / 1 ER / 11 K — MLB-leading 6th W and a Coors line that's almost unheard of. Drake Baldwin (3-for-4, 4 RBI) opened the scoring with a 2-run HR (#8) off COL LHP Brennan Bernardino (LP, 2-1) in the 1st, then doubled and singled — a triple short of the cycle. Olson #11 (now MLB co-leader) and Riley #4 added insurance. Lone scare: Ronald Acuña Jr. exited in the 2nd inning with left hamstring tightness after pulling up halfway down the line on a grounder; he walked off gingerly and will undergo an MRI. Atlanta now 14 of last 17, 7.5+ GM up on MIA in the NL East and best record in MLB by 1.5 over LAD." },
  { date: "2026-05-01", opp: "COL", home: false, atlScore: 8, oppScore: 6, result: "W", note: "INSTANT CLASSIC AT COORS — Atlanta erased a 6-0 deficit with EIGHT UNANSWERED runs, capped by Michael Harris II's pinch-hit 2-run HR off Tyler Kinley in the 9th. Tied for the franchise's largest comeback ever at Coors Field. Holmes got bullied by altitude (4 IP / 4 ER / 6 H, ND); Quintana matched zeros for COL through 4. The Braves scratched a run in the 7th, then exploded for 4 in the 8th — Mauricio Dubón's BASES-LOADED TRIPLE the dagger that tied it 6-6, with Olson's #10 HR fueling the cushion. Didier Fuentes (W, 1-0) went 2 scoreless out of the pen (5th–6th, 3 K). Pierce Johnson worked a clean 9th for his first save. Atlanta moves to 23-10 and 7.5 GM up on MIA. Pregame: Suárez and Payamps DFA'd; Stratton and Molina recalled/selected from Triple-A Gwinnett." },
  { date: "2026-04-30", opp: "DET", home: true,  atlScore: 2, oppScore: 5, result: "L", note: "Tigers avoid the sweep with a 4-run 8th. Bryce Elder (ND) was excellent: 6 IP / 6 H / 1 ER / 3 BB / 5 K, exiting with a 2-1 lead. Joel Payamps gave up Carpenter's leadoff triple to start the 8th and Vierling's tying double chased him; Aaron Bummer relieved, walked McGonigle, then Gleyber Torres's go-ahead sac fly made it 3-2. José Suárez (LP) walked Pérez and Hao-Yu Lee in the 9th, Yastrzemski misplayed Vierling's third hit for an error, and Dingler's double iced it at 5-2. Atlanta still takes the series 2-1; the 10-game ATL streak vs DET ends. Tigers finish April 14-13 and stay atop the AL Central at 16-16 on the trip." },
  { date: "2026-04-29", opp: "DET", home: true,  atlScore: 4, oppScore: 3, result: "W", note: "WALK-OFF — Matt Olson clubbed a 2-run, 397-ft HR (#9) into the Atlanta bullpen off ex-Brave Kenley Jansen on the 5th pitch of the AB, after Albies opened the 9th with a walk. Spoiled a dominant Tarik Skubal start (7 IP / 5 H / 2 ER / 0 BB / 7 K, 91 pitches) — Albies 2-run HR (#7) in the 1st was Atlanta's only damage off the AL Cy Young. JR Ritchie pitched into the 6th in his second MLB start (ND); a pickoff-throw error on McGonigle in the 2nd let DET tie it. Reynaldo López (W, 2-1) was the difference: 2 scoreless / 0 H / 2 K out of the pen in the 8th–9th. Tigers closer Jansen has now allowed walk-off HRs in back-to-back outings." },
  { date: "2026-04-28", opp: "DET", home: true,  atlScore: 5, oppScore: 2, result: "W", note: "Martín Pérez (W, 2-1) tossed 5 scoreless on 2 H / 4 BB / 5 K in the series opener vs the AL Central champs — first W over Detroit since Aug 25, 2019. Yastrzemski/Acuña hit back-to-back doubles in the 3rd, Acuña scored on Olson's sac fly for a 2-0 lead, and Albies smashed a 2-run HR (#6, 377 ft, 98.5 mph EV) off Tyler Holton in the 8th to put it away. DET RHP Casey Mize (LP, 2-2) left after 2.1 IP with right groin tightness. Atlanta improves to 21-9, tied with LAD for best in MLB." },
  { date: "2026-04-26", opp: "PHI", home: true,  atlScore: 6, oppScore: 2, result: "W", note: "Sale's 150th career W and a season-high 9 K across 6 shutout IP / 1 H on 88 pitches. Olson 3-run HR off Nola in the 1st (#9, 4th career off Nola), Eli White 2-run HR in the 2nd. Acuña 2-3, R, SB. Schwarber 2-run HR off the pen in the 8th avoided the shutout. ATL takes the series 2-1 — first MLB team to 20 wins; 10-2 in last 12. Pregame: Brian Snitker inducted into the Braves Hall of Fame." },
];

// ─── NL EAST STANDINGS ──────────────────────────────────────────────────────────
export const NL_EAST_STANDINGS = [
  { team: "ATL", name: "Atlanta Braves",         w: 26, l: 12, pct: .684, gb: 0,    streak: "L1" },
  { team: "PHI", name: "Philadelphia Phillies",  w: 17, l: 20, pct: .459, gb: 8.5,  streak: "W4" },
  { team: "MIA", name: "Miami Marlins",          w: 16, l: 21, pct: .432, gb: 9.5,  streak: "L4" },
  { team: "WSH", name: "Washington Nationals",   w: 16, l: 21, pct: .432, gb: 9.5,  streak: "L2" },
  { team: "NYM", name: "New York Mets",          w: 14, l: 22, pct: .389, gb: 11,   streak: "W3" },
];

// ─── NEWS DIGEST — the recency-biased summary the skill refreshes daily ──────────
export const NEWS_DIGEST = {
  generatedAt: "2026-05-07T09:00:00-04:00",
  summary:
    "FIRST SERIES LOSS, JARVIS DEBUTS, BRAVES TURN WEST FOR LA — Atlanta's flat-line bats finally caught up with them in the Seattle rubber match: Bryan Woo (W, 2-2) tied his season high with NINE strikeouts across 6 scoreless IP, Julio Rodríguez homered, José Ferrer saved it, and the Mariners took it 3-1. Atlanta managed just 4 hits and 2 walks against the SEA staff, with Mauricio Dubón's two-out single in the 4th the only knock off Woo. Martín Pérez (LP, 2-2) was tough-luck: 5.2 IP / 5 H / 2 ER / 3 BB / 5 K — a quality start with no run support. The eight-series win streak (and the historic 10-0-1 start to the season) is officially over. ATL drops to 26-12 (.684) but still leads PHI by 8.5 in the NL East, MLB-best record. Pregame roster move: 25-year-old INFIELDER JIM JARVIS selected from Triple-A Gwinnett (.305/.418/.445, 4 HR, 15 SB across 33 G) for his MLB DEBUT — started at SS batting 9th to spell Mateo. José Azocar DFA'd in the corresponding move three days after his selection. Today is a TRAVEL DAY ahead of a marquee three-game series at DODGER STADIUM (away) starting Friday: Sale (6-1, 2.14) vs Emmet Sheehan in the opener. Acuña Jr. remains on the 10-day IL (Grade 1 hamstring), Harris stays DH-only ~7 days, Murphy easing back in, Iglesias secured his 6th save Tuesday. Dodd's Triple-A Gwinnett rehab outing went well — he could rejoin the pen by Friday's series opener.",
  keyTopics: [
    { category: "result",      title: "L 1-3 at SEA — Woo 6 IP / 9 K shuts down Atlanta in series finale",                detail: "Bryan Woo (W, 2-2) tied a season-high with 9 K across 6 scoreless IP on a season-high 98 pitches; Atlanta's lone hit off him was Mauricio Dubón's two-out single in the 4th. ATL finished with 4 H, 2 BB, 12 K total. Cole Young (3-for-4, 2 doubles) added an RBI 2B in the 3rd; Julio Rodríguez (HR #5) went deep off Pérez in the 6th. José Ferrer pitched a 1-2-3 9th for his 2nd save. Pérez (LP, 2-2): 5.2 IP / 5 H / 2 ER / 3 BB / 5 K. Atlanta's first series loss of 2026." },
    { category: "transaction", title: "BRAVES SELECT JIM JARVIS FOR MLB DEBUT — Azocar DFA'd",                              detail: "Atlanta selected the contract of 25-yo IF Jim Jarvis from Triple-A Gwinnett, where he was raking (.305/.418/.445, 4 HR, 15 SB across 33 G). The Alabama product (11th rd, 2023 DET pick; acquired by ATL at the 2025 deadline for Rafael Montero) made his MLB debut at SS batting 9th. José Azocar DFA'd in the corresponding move — likely outright to Triple-A within 5 days. Jarvis profiles as a versatile utility infielder rather than a one-spot regular." },
    { category: "rotation",    title: "Pérez bumped UP a day for SEA finale — Holmes pushed back to Tue 5/12",              detail: "With the rotation needing length and the LAD series looming, Walt Weiss flipped his Wed-Sat order — Pérez took the ball Wednesday on 5 days' rest, and Grant Holmes is now lined up for the Tuesday WSH homestand opener (May 12). The decision lined Sale up for the Friday Dodger Stadium opener on his regular turn rather than burning a day with Holmes at altitude-adjacent SEA." },
    { category: "rotation",    title: "FRIDAY: Sale (6-1, 2.14) vs Sheehan at Dodger Stadium",                              detail: "MARQUEE OPENER — Chris Sale starts his personal 4-game W streak at Dodger Stadium opposite Emmet Sheehan, who's coming off a 4-ER L in St. Louis with 8 K and 0 BB last Friday. Sale's 49 K still leads the NL; his 2.14 ERA and 0.83 WHIP top the team. First pitch 7:10 PT / 10:10 PM ET. The full LAD series: Sale Fri, Ritchie Sat, Elder Sun (Mother's Day matinee)." },
    { category: "transaction", title: "DODD'S REHAB OUTING WENT WELL — likely activated by Friday",                         detail: "LHP Dylan Dodd (left thoracic spine inflammation, 15-day IL since Apr 23) made a clean rehab outing for Triple-A Gwinnett Tuesday and is on track to be reinstated for the LAD opener Friday at Dodger Stadium, restoring a third lefty in the bullpen alongside Bummer and Lee. Corresponding move TBD but likely a swingman optioned out." },
    { category: "injury",      title: "Acuña Jr. continues 10-day IL stay (Grade 1 hamstring)",                             detail: "Acuña remains on the 10-day IL (placed May 3, retroactive) — MRI confirmed a Grade 1 left hamstring strain. Typical Grade 1 returns are 2-4 weeks; mid-to-late-May target. Eli White / Bairon Velandia / Jorge Mateo continue to absorb RF reps; ATL went 3-3 across the COL/SEA road trip without him." },
    { category: "injury",      title: "HARRIS II stays DH-ONLY for ~7 days; no IL trip",                                    detail: "Walt Weiss reaffirmed Atlanta will use Michael Harris II exclusively at DH for ~7 days to nurse the left quad — too productive (.322/.357/.561, 7 HR, 22 RBI in 31 G) to send to the IL unless the leg gets worse. White and Velandia split the CF reps; this also keeps Harris's bat in vs RHP at LAD without exposing him on the basepaths." },
    { category: "milestone",   title: "OLSON still NL HR leader (13) — 1.019 OPS through 36 G",                             detail: "Olson cooled with the rest of the lineup Wednesday (1-for-4, 2 K vs Woo) but his 9th-inning go-ahead bomb Tuesday — back-to-back nights with HRs after Monday's 428-ft 300th career — keeps him at 13 HR, NL-leading. .302/.372/.647, 33 RBI through 36 G. He's the centerpiece of an offense that's surviving Acuña's 10-day absence." },
    { category: "narrative",   title: "Eight-series win streak (10-0-1 start) is over",                                     detail: "Atlanta entered Wednesday on an 11-series unbeaten run — the fifth team in the Wild Card era (since 1995) to start a season unbeaten in 11+ straight series. The 3-1 L in Seattle officially ends the streak at 10-0-1, with the Mariners taking the rubber match in a Woo masterclass. Weiss-led ATL still owns MLB's best record." },
    { category: "milestone",   title: "Sale's 49 K still leads the NL; lined up for LAD opener",                            detail: "Saturday's 7 IP / 11 K / 1 ER at Coors keeps Sale at 49 K (NL leader), 2.14 ERA, 0.83 WHIP, 6 W (MLB co-leader). Friday's Dodger Stadium start vs Sheehan is the next-most-watched start of his season — Atlanta's stiffest test of the year vs the defending champs in their building." },
    { category: "injury",      title: "Kim continues rehab — bumped up to Triple-A Gwinnett",                               detail: "Ha-Seong Kim's right middle finger torn tendon (Jan 2026 surgery) rehab moved up a level Tuesday: Atlanta transferred his rehab assignment from Double-A Columbus to Triple-A Gwinnett. Weiss still targeting mid-May for the activation. Dubón continues to bridge at SS (his single Wed was Atlanta's only hit off Woo); Mateo and Jarvis split the secondary middle-IF reps." },
    { category: "standings",   title: "NL East: ATL still +8.5 on PHI; W4 streak in Philly",                                detail: "ATL 26-12 (.684) — still MLB-best — leads PHI 17-20 (W4 after sweeping Oakland) by 8.5. MIA 16-21 (L4) and WSH 16-21 (L2) tied at 9.5 GB; NYM 14-22 (.389, W3) at 11 GB. Atlanta's lead trimmed by a game on the day but remains comfortable; the LAD series and the ensuing NYM/WSH stretch will be the first real adversity test." },
  ],
  sources: [
    "MLB.com", "ESPN", "AJC", "Battery Power", "MLB Trade Rumors", "CBS Sports", "Yahoo Sports", "Baseball-Reference", "FanGraphs", "Lookout Landing", "AP", "Atlanta News First", "Yardbarker", "Heavy.com", "Fox Sports", "RotoWire", "FantasyPros", "MyNorthwest", "True Blue LA", "Spokesman-Review", "Roll Tide", "Saturday Down South", "Dodger Blue",
  ],
};
